// Sakbank: vanliga föremål som användaren kan välja till sin personliga lista
// och öva på i Snabbkoll-bildspelet. Ingen AI behövs för katalogen.

export const itemBankCategories = Object.freeze([
  { icon: '🔑', id: 'essentials', label: 'Viktigast' },
  { icon: '📱', id: 'electronics', label: 'Elektronik' },
  { icon: '👕', id: 'clothes', label: 'Kläder' },
  { icon: '🧴', id: 'hygiene', label: 'Hygien' },
  { icon: '💊', id: 'health', label: 'Hälsa' },
  { icon: '🍎', id: 'food', label: 'Mat & dryck' },
  { icon: '💼', id: 'work', label: 'Jobb & skola' },
  { icon: '🏋️', id: 'sport', label: 'Träning' },
  { icon: '🧳', id: 'travel', label: 'Resa' },
  { icon: '👶', id: 'family', label: 'Barn & familj' },
  { icon: '🏠', id: 'home', label: 'Hemma' },
])

// [id, ikon, namn, kategori, sökord]
const rawItems = [
  // Viktigast
  ['keys', '🔑', 'Nycklar', 'essentials', 'husnycklar bilnycklar nyckelknippa'],
  ['wallet', '👛', 'Plånbok', 'essentials', 'portmonnä'],
  ['phone', '📱', 'Mobil', 'essentials', 'telefon iphone android'],
  ['id-card', '🪪', 'ID-kort', 'essentials', 'legitimation körkort leg'],
  ['bank-card', '💳', 'Bankkort', 'essentials', 'kort betalkort kreditkort'],
  ['travel-card', '🎫', 'Busskort', 'essentials', 'sl-kort reskort periodkort biljett'],
  ['glasses', '👓', 'Glasögon', 'essentials', 'läsglasögon'],
  ['sunglasses', '🕶️', 'Solglasögon', 'essentials', 'sol'],
  ['cash', '💵', 'Kontanter', 'essentials', 'pengar sedlar mynt'],
  ['access-badge', '🏷️', 'Passerkort', 'essentials', 'tagg bricka nyckelbricka'],
  ['umbrella', '☂️', 'Paraply', 'essentials', 'regn'],
  ['bag', '👜', 'Väska', 'essentials', 'handväska axelväska'],
  // Elektronik
  ['charger', '🔌', 'Laddare', 'electronics', 'mobilladdare sladd'],
  ['power-bank', '🔋', 'Powerbank', 'electronics', 'batteri reservbatteri'],
  ['headphones', '🎧', 'Hörlurar', 'electronics', 'lurar'],
  ['earbuds', '🎵', 'Trådlösa hörlurar', 'electronics', 'airpods earbuds'],
  ['laptop', '💻', 'Dator', 'electronics', 'laptop bärbar'],
  ['laptop-charger', '🔌', 'Datorladdare', 'electronics', 'sladd adapter'],
  ['tablet', '📲', 'Surfplatta', 'electronics', 'ipad platta'],
  ['smartwatch', '⌚', 'Klocka', 'electronics', 'smartklocka armbandsur'],
  ['usb-cable', '🔗', 'USB-kabel', 'electronics', 'kabel sladd'],
  ['usb-stick', '💾', 'USB-minne', 'electronics', 'minnessticka'],
  ['camera', '📷', 'Kamera', 'electronics', 'systemkamera'],
  ['hearing-aid', '🦻', 'Hörapparat', 'electronics', 'hörsel'],
  // Kläder
  ['jacket', '🧥', 'Jacka', 'clothes', 'rock kappa'],
  ['sweater', '👕', 'Tröja', 'clothes', 'kofta hoodie'],
  ['shoes', '👟', 'Skor', 'clothes', 'sneakers gympaskor'],
  ['boots', '🥾', 'Kängor', 'clothes', 'stövlar vinterskor'],
  ['cap', '🧢', 'Keps', 'clothes', 'hatt'],
  ['beanie', '🧶', 'Mössa', 'clothes', 'vintermössa'],
  ['scarf', '🧣', 'Halsduk', 'clothes', 'sjal'],
  ['gloves', '🧤', 'Vantar', 'clothes', 'handskar'],
  ['socks', '🧦', 'Strumpor', 'clothes', 'sockor'],
  ['underwear', '🩲', 'Underkläder', 'clothes', 'kalsonger trosor'],
  ['trousers', '👖', 'Byxor', 'clothes', 'jeans'],
  ['dress', '👗', 'Klänning', 'clothes', 'kjol'],
  ['rain-jacket', '🌧️', 'Regnjacka', 'clothes', 'regnkläder'],
  ['change-of-clothes', '🎽', 'Ombyte', 'clothes', 'extrakläder'],
  // Hygien
  ['toothbrush', '🪥', 'Tandborste', 'hygiene', 'tänder'],
  ['toothpaste', '🦷', 'Tandkräm', 'hygiene', 'tänder'],
  ['deodorant', '🧴', 'Deodorant', 'hygiene', 'deo'],
  ['hairbrush', '💇', 'Hårborste', 'hygiene', 'kam'],
  ['hand-sanitizer', '🧼', 'Handsprit', 'hygiene', 'handdesinfektion tvål'],
  ['tissues', '🤧', 'Näsdukar', 'hygiene', 'pappersnäsdukar'],
  ['lip-balm', '💄', 'Cerat', 'hygiene', 'läppbalsam läppstift'],
  ['sunscreen', '🌞', 'Solkräm', 'hygiene', 'solskydd'],
  ['razor', '🪒', 'Rakhyvel', 'hygiene', 'rakning'],
  ['towel', '🛁', 'Handduk', 'hygiene', 'badlakan'],
  ['menstrual-products', '🩸', 'Mensskydd', 'hygiene', 'binda tampong'],
  ['wet-wipes', '🧻', 'Våtservetter', 'hygiene', 'servetter papper'],
  // Hälsa
  ['medicine', '💊', 'Mediciner', 'health', 'tabletter läkemedel'],
  ['pill-organizer', '🗓️', 'Dosett', 'health', 'medicinask'],
  ['inhaler', '🌬️', 'Inhalator', 'health', 'astma'],
  ['plasters', '🩹', 'Plåster', 'health', 'förband'],
  ['painkillers', '🩺', 'Värktabletter', 'health', 'alvedon ipren'],
  ['epipen', '💉', 'Adrenalinpenna', 'health', 'epipen allergi'],
  ['glucose-meter', '🩸', 'Blodsockermätare', 'health', 'diabetes'],
  ['face-mask', '😷', 'Munskydd', 'health', 'mask'],
  ['contact-lenses', '👁️', 'Linser', 'health', 'kontaktlinser'],
  ['prescription', '📄', 'Recept', 'health', 'e-recept'],
  // Mat & dryck
  ['water-bottle', '🚰', 'Vattenflaska', 'food', 'vatten flaska'],
  ['lunchbox', '🍱', 'Matlåda', 'food', 'lunch'],
  ['snack', '🍎', 'Mellanmål', 'food', 'frukt snacks'],
  ['banana', '🍌', 'Banan', 'food', 'frukt'],
  ['coffee-cup', '☕', 'Kaffemugg', 'food', 'termos kopp'],
  ['thermos', '🫖', 'Termos', 'food', 'te'],
  ['cutlery', '🍴', 'Bestick', 'food', 'gaffel kniv sked'],
  ['protein-bar', '🍫', 'Proteinbar', 'food', 'bar choklad'],
  ['sandwich', '🥪', 'Smörgås', 'food', 'macka'],
  ['shopping-bag', '🛍️', 'Kasse', 'food', 'påse tygpåse'],
  // Jobb & skola
  ['notebook', '📓', 'Anteckningsbok', 'work', 'block'],
  ['pen', '🖊️', 'Penna', 'work', 'kulspetspenna'],
  ['pencil-case', '✏️', 'Pennfodral', 'work', 'pennor'],
  ['documents', '📁', 'Papper', 'work', 'dokument mapp'],
  ['books', '📚', 'Böcker', 'work', 'bok läxor'],
  ['calculator', '🧮', 'Miniräknare', 'work', 'räknare'],
  ['work-badge', '🪪', 'Jobbkort', 'work', 'id-bricka'],
  ['backpack', '🎒', 'Ryggsäck', 'work', 'skolväska'],
  ['calendar', '📅', 'Kalender', 'work', 'almanacka'],
  ['briefcase', '💼', 'Portfölj', 'work', 'jobbväska'],
  // Träning
  ['gym-bag', '👝', 'Träningsväska', 'sport', 'gymväska'],
  ['gym-clothes', '🩳', 'Träningskläder', 'sport', 'shorts tights'],
  ['running-shoes', '👟', 'Löparskor', 'sport', 'träningsskor'],
  ['gym-card', '🏋️', 'Gymkort', 'sport', 'medlemskort'],
  ['padlock', '🔒', 'Hänglås', 'sport', 'lås skåp'],
  ['swimwear', '🩱', 'Badkläder', 'sport', 'baddräkt badbyxor bikini'],
  ['yoga-mat', '🧘', 'Yogamatta', 'sport', 'matta'],
  ['bike-helmet', '🪖', 'Cykelhjälm', 'sport', 'hjälm'],
  ['bike-lock', '🚲', 'Cykellås', 'sport', 'cykel'],
  ['reflector', '✨', 'Reflex', 'sport', 'reflexväst'],
  // Resa
  ['passport', '🛂', 'Pass', 'travel', 'resehandling'],
  ['tickets', '🎟️', 'Biljetter', 'travel', 'boardingkort flygbiljett'],
  ['suitcase', '🧳', 'Resväska', 'travel', 'väska'],
  ['travel-adapter', '🔌', 'Reseadapter', 'travel', 'adapter uttag'],
  ['neck-pillow', '😴', 'Nackkudde', 'travel', 'kudde'],
  ['insurance-card', '🛡️', 'Försäkringskort', 'travel', 'europeiska sjukförsäkringskortet'],
  ['map', '🗺️', 'Karta', 'travel', 'vägbeskrivning'],
  ['hotel-booking', '🏨', 'Hotellbokning', 'travel', 'bokning'],
  ['currency', '💶', 'Valuta', 'travel', 'euro utländska pengar'],
  // Barn & familj
  ['diapers', '👶', 'Blöjor', 'family', 'blöja'],
  ['baby-bottle', '🍼', 'Nappflaska', 'family', 'flaska mjölk'],
  ['pacifier', '🍭', 'Napp', 'family', 'tutt'],
  ['toy', '🧸', 'Leksak', 'family', 'gosedjur nalle'],
  ['stroller', '🛒', 'Barnvagn', 'family', 'vagn sittvagn'],
  ['kids-snack', '🧃', 'Barnens mellanmål', 'family', 'juice'],
  ['spare-clothes-kids', '👚', 'Extrakläder barn', 'family', 'ombyte barn'],
  ['dog-leash', '🐕', 'Hundkoppel', 'family', 'koppel hund'],
  ['poop-bags', '🗑️', 'Bajspåsar', 'family', 'hundpåsar'],
  // Hemma
  ['stove-off', '🔥', 'Spisen avstängd', 'home', 'spis ugn'],
  ['windows-closed', '🪟', 'Fönster stängda', 'home', 'fönster'],
  ['lights-off', '💡', 'Lampor släckta', 'home', 'lampa ljus'],
  ['trash', '🚮', 'Soporna', 'home', 'sopor skräp'],
  ['mail', '✉️', 'Post', 'home', 'brev'],
  ['plants', '🪴', 'Vattna blommor', 'home', 'växter'],
  ['door-locked', '🚪', 'Dörren låst', 'home', 'lås ytterdörr'],
  ['iron-off', '🧺', 'Strykjärn avstängt', 'home', 'tvätt'],
]

export const itemBankCatalog = Object.freeze(rawItems.map(([id, icon, label, category, keywords]) => Object.freeze({
  category,
  custom: false,
  icon,
  id,
  keywords: keywords || '',
  label,
})))

export const itemBankCatalogSize = itemBankCatalog.length
