export const moreHubFolders = [
  {
    id: 'mal-framsteg',
    accent: 'gold',
    description: 'Vikt, mål, achievements och rapporter',
    icon: '◎',
    title: 'Framsteg',
  },
  {
    id: 'mat',
    accent: 'magenta',
    description: 'Mat, måltider och matscanning',
    icon: '+',
    title: 'Mat',
  },
  {
    id: 'ai-coach',
    accent: 'cyan',
    description: 'Fullständig AI Coach',
    icon: '✦',
    title: 'AI Coach',
  },
  {
    id: 'ma-bra',
    accent: 'purple',
    description: 'Lugna övningar och trygghetsplan',
    icon: '♡',
    title: 'Må bra',
  },
  {
    id: 'ekonomi',
    accent: 'green',
    description: 'Utgifter, budget, skulder och sparande',
    icon: '◌',
    title: 'Ekonomi',
  },
  {
    id: 'sign-language',
    accent: 'cyan',
    description: 'STS, fraser och säkra framtida teckenstöd',
    icon: '手',
    title: 'Teckenspråk',
  },
  {
    id: 'animal-world',
    accent: 'blue',
    description: 'Djur, insekter och faktagranskade videospår',
    icon: '◇',
    title: 'Djurvärlden',
  },
  {
    id: 'pregnancy-first-year',
    accent: 'magenta',
    description: 'Graviditet, första året och vårdhänvisningar',
    icon: '◉',
    title: 'Graviditet & första året',
  },
  {
    id: 'sakerhet-backup',
    accent: 'purple',
    description: 'Backup, återställ, synk, moln',
    icon: '☁',
    title: 'Säkerhet & Backup',
  },
  {
    id: 'import-export',
    accent: 'blue',
    description: 'Dataimport, dataexport',
    icon: '⇄',
    title: 'Import & Export',
  },
  {
    id: 'arkiv-historik',
    accent: 'orange',
    description: 'Backup-historik, loggar',
    icon: '▤',
    title: 'Arkiv & Historik',
  },
  {
    id: 'installningar',
    accent: 'green',
    description: 'Appinställningar, enheter',
    icon: '⚙',
    title: 'Inställningar',
  },
]

export const moreHubTargetFolders = {
  'ai-coach': 'ai-coach',
  'animal-world': 'animal-world',
  'app-section-coach': 'ai-coach',
  'app-section-animal-world': 'animal-world',
  'app-section-nutrition': 'mat',
  'app-section-progress': 'mal-framsteg',
  'app-section-economy': 'ekonomi',
  'app-section-pregnancy-first-year': 'pregnancy-first-year',
  'app-section-sign-language': 'sign-language',
  'arkiv-historik': 'arkiv-historik',
  'backup-historik': 'arkiv-historik',
  'body-analysis': 'mal-framsteg',
  'cloud-sync': 'sakerhet-backup',
  'dagliga-paminnelser': 'mal-framsteg',
  'data-export': 'import-export',
  'data-import': 'import-export',
  framstegsbilder: 'mal-framsteg',
  installningar: 'installningar',
  ekonomi: 'ekonomi',
  graviditet: 'pregnancy-first-year',
  mat: 'mat',
  'mal-framsteg': 'mal-framsteg',
  'mal-framsteg-oversikt': 'mal-framsteg',
  'ma-bra': 'ma-bra',
  'pregnancy-first-year': 'pregnancy-first-year',
  molnbackup: 'sakerhet-backup',
  molnstatus: 'sakerhet-backup',
  'notification-center': 'mal-framsteg',
  'nutrition-scanner-v2': 'mat',
  'progress-insights': 'mal-framsteg',
  'quiet-hours': 'mal-framsteg',
  rapportcenter: 'mal-framsteg',
  'reminder-center': 'mal-framsteg',
  sakerhet: 'sakerhet-backup',
  scanner: 'mat',
  'sign-language': 'sign-language',
  teckensprak: 'sign-language',
  teckenspråk: 'sign-language',
  vikt: 'mal-framsteg',
  wellbeing: 'ma-bra',
  'wellbeing-center': 'ma-bra',
  'app-section-wellbeing': 'ma-bra',
  economy: 'ekonomi',
  'economy-center': 'ekonomi',
}

export function resolveMoreFolderFromTarget(targetId) {
  const id = String(targetId || '').replace(/^#/, '')
  if (!id || id === 'app-section-more' || id === 'more') return null
  if (moreHubFolders.some((folder) => folder.id === id)) return id
  return moreHubTargetFolders[id] || null
}
