/**
 * Language-neutral product facts for AI Help.
 * Stable ids stay the same when copy is revised.
 * Text is Swedish source. The model answers in the user's app language.
 * This is a feature map, not a list of scripted questions.
 * Prices stay out of this file. Preliminary plan facts are added on the server.
 */
export const knowledgeCatalog = [
  {
    id: 'help.scope',
    title: 'AI-Hjälp',
    aliases: ['hjälp', 'help', 'kundtjänst', 'support', 'guide'],
    summary: 'AI-Hjälpen förklarar hur Viktkollen används. Den är inte AI-coachen och ger inte hälso-, kost- eller träningsråd. Den kan inte ändra konto, betalning eller abonnemang.',
    steps: [],
    status: 'implemented',
    sectionId: 'installningar',
  },
  {
    id: 'navigation.home',
    title: 'Hem',
    aliases: ['hem', 'start', 'dashboard', 'översikt'],
    summary: 'Hem är den första länken i den nedre navigeringen. Där samlas översikt, veckans läge, notiser och genvägar.',
    steps: ['Tryck på Hem i den nedre navigeringen.'],
    status: 'implemented',
    sectionId: 'home',
  },
  {
    id: 'navigation.redo',
    title: 'Redo!',
    aliases: ['redo', 'checklista', 'väska'],
    summary: 'Redo! är en länk i den nedre navigeringen. Där finns checklistor och ingången till AI Ögat.',
    steps: ['Tryck på Redo! i den nedre navigeringen.'],
    status: 'implemented',
    sectionId: 'redo',
  },
  {
    id: 'navigation.place',
    title: 'Plats',
    aliases: ['plats', 'place', 'karta'],
    summary: 'Plats är en länk i den nedre navigeringen. Familjekarta och delning av position är förberedda men inte anslutna. Ingen familjeposition delas förrän ett samtycke finns, och kartan är ändå inte ansluten.',
    steps: ['Tryck på Plats i den nedre navigeringen.'],
    status: 'partial',
    sectionId: 'place',
  },
  {
    id: 'navigation.journey',
    title: 'Min resa',
    aliases: ['min resa', 'resan', 'journey'],
    summary: 'Min resa är en egen länk i den nedre navigeringen, tillsammans med Hem, Redo!, Plats, Stället och Mer. Den samlar översikt, framsteg, mat, aktivitet, mål, coach och rapporter. Den är inte mappen Framsteg under Mer.',
    steps: ['Tryck på Min resa i den nedre navigeringen.'],
    status: 'implemented',
    sectionId: 'journey',
  },
  {
    id: 'navigation.social',
    title: 'Stället',
    aliases: ['stället', 'socialt', 'social'],
    summary: 'Stället är en länk i den nedre navigeringen. Den kan döljas om funktionen stängs av.',
    steps: ['Tryck på Stället i den nedre navigeringen.'],
    status: 'implemented',
    sectionId: 'social',
  },
  {
    id: 'navigation.more',
    title: 'Mer-menyn',
    aliases: ['mer', 'more', 'meny', 'navigation'],
    summary: 'Mer är den sista länken i den nedre navigeringen. Den öppnar appens mappar, bland annat Framsteg, Mat, Inställningar och AI-Hjälp.',
    steps: ['Tryck på Mer i den nedre navigeringen.'],
    status: 'implemented',
    sectionId: 'more',
  },
  {
    id: 'navigation.notices',
    title: 'Notiser',
    aliases: ['notis', 'notiser', 'avisering'],
    summary: 'Notiser finns som ett eget avsnitt när påminnelseytan är på. Notiser är inte en länk i den nedre navigeringen. Min resa upptar den platsen.',
    steps: ['Öppna notisavsnittet från Hem eller påminnelserna.'],
    status: 'implemented',
    sectionId: 'notices',
  },
  {
    id: 'more.progress',
    title: 'Framsteg',
    aliases: ['framsteg', 'progress'],
    summary: 'Framsteg under Mer är mappen för viktgraf, framstegsbilder, mål, kroppsscanning, achievements och rapporter. Min resa är en separat länk i den nedre navigeringen.',
    steps: ['Öppna Mer.', 'Öppna Framsteg.'],
    status: 'implemented',
    sectionId: 'progress',
  },
  {
    id: 'feature.weight-history',
    title: 'Viktgraf',
    aliases: ['viktgraf', 'viktkurva', 'viktutveckling', 'vikthistorik', 'vikt', 'förändring'],
    summary: 'Viktgrafen visar hur den uppmätta eller användarinmatade vikten har förändrats. Den finns under Framsteg.',
    steps: ['Öppna Mer.', 'Öppna Framsteg.', 'Läs viktgrafen där.'],
    limits: 'Grafen blandar inte in AI-estimat från kroppsscanningen.',
    status: 'implemented',
    sectionId: 'progress',
  },
  {
    id: 'feature.progress-photos',
    title: 'Framstegsbilder',
    aliases: ['framstegsbilder', 'progressbilder', 'före efter', 'bilder', 'foto'],
    summary: 'Framstegsbilder är sparade bilder och före/efter-jämförelse under Framsteg.',
    steps: ['Öppna Mer.', 'Öppna Framsteg.', 'Öppna framstegsbilderna.'],
    limits: 'AI-Hjälpen kan inte visa eller ladda upp bilderna själv.',
    status: 'implemented',
    sectionId: 'progress',
  },
  {
    id: 'feature.body-scan',
    title: 'Kroppsscanning',
    aliases: ['kroppsscanning', 'kroppsanalys', 'body scan', 'bodyscan'],
    summary: 'Kroppsscanning är en guidad kameragenomgång med fram-, sido- och bakbild. Den finns under Framsteg. Mikrofonen används inte.',
    steps: ['Öppna Mer.', 'Öppna Framsteg.', 'Öppna kroppsscanningen.'],
    status: 'implemented',
    sectionId: 'progress',
  },
  {
    id: 'more.nutrition',
    title: 'Mat',
    aliases: ['mat', 'måltid', 'måltider', 'matscanning', 'nutrition', 'food', 'recept'],
    summary: 'Mat samlar måltider, matscanning med kamera eller streckkod, matplan och recept. AI-Hjälpen ger inte egna matrecept eller kostråd.',
    steps: ['Öppna Mer.', 'Öppna Mat.'],
    status: 'implemented',
    sectionId: 'nutrition',
  },
  {
    id: 'more.activity',
    title: 'Aktivitet',
    aliases: ['aktivitet', 'steg', 'träning', 'activity', 'steps'],
    summary: 'Aktivitet samlar steg, träning, distans och aktiv tid.',
    steps: ['Öppna Mer.', 'Öppna Aktivitet.'],
    status: 'implemented',
    sectionId: 'aktivitet',
  },
  {
    id: 'more.coach',
    title: 'AI Coach',
    aliases: ['coach', 'ai-coach', 'röst', 'mikrofon', 'prata'],
    summary: 'AI Coach är en separat funktion för hälsa, kost och träning. Den öppnas från Mer. Röstläge använder mikrofonen när du själv trycker på den. AI-Hjälpen är inte coachen.',
    steps: ['Öppna Mer.', 'Öppna AI Coach.'],
    status: 'implemented',
    sectionId: 'coach',
  },
  {
    id: 'feature.ai-eye',
    title: 'AI Ögat',
    aliases: ['ai ögat', 'ögat', 'ai-ögat', 'kameran i redo'],
    summary: 'AI Ögat finns i Redo! och är förberett i gränssnittet. Ingen generell föremålsanalys är ansluten. Ingen bild skickas och ingen låtsasanalys visas som riktig AI.',
    steps: ['Öppna Redo! i den nedre navigeringen.', 'Öppna AI Ögat.'],
    status: 'partial',
    sectionId: 'redo',
  },
  {
    id: 'feature.ai-ear',
    title: 'AI Örat',
    aliases: ['ai örat', 'ai-örat', 'örat', 'ljudigenkänning', 'fågelljud', 'tal till text', 'humma', 'sjung'],
    summary: 'AI Örat öppnas i Smart kamera på Hem, och från Mer under Tillgänglighet och Hörsel. Ljudigenkänning och fågelljud skickas till Viktkollens server först när du själv analyserar. Tal till text görs i webbläsaren och skickar inget ljud dit. Humma eller sjung visas i gränssnittet, skickar inget ljud och har ingen ansluten melodiigenkänning. Resultatet är en indikation.',
    steps: ['Öppna Hem.', 'Öppna Smart kamera.', 'Välj AI Örat.'],
    status: 'partial',
    sectionId: 'home',
  },
  {
    id: 'feature.family-map',
    title: 'Familjekarta',
    aliases: ['familjekarta', 'familj', 'gps', 'position'],
    summary: 'Familjekarta ligger under Plats. Den är inte ansluten. Position till familjen delas inte, även om samtycke senare kan krävas för andra platsfunktioner.',
    steps: ['Öppna Plats i den nedre navigeringen.'],
    status: 'partial',
    sectionId: 'place',
  },
  {
    id: 'feature.reminders',
    title: 'Påminnelser',
    aliases: ['påminnelse', 'påminnelser', 'reminder', 'snooze'],
    summary: 'Påminnelser och notiscenter hanteras från Framsteg och notisavsnittet. AI-Hjälpen kan inte skapa eller ändra en påminnelse.',
    steps: ['Öppna Mer.', 'Öppna Framsteg.'],
    status: 'implemented',
    sectionId: 'progress',
  },
  {
    id: 'more.wellbeing',
    title: 'Må bra',
    aliases: ['må bra', 'wellbeing', 'trygghet'],
    summary: 'Må bra innehåller lugna övningar och en trygghetsplan.',
    steps: ['Öppna Mer.', 'Öppna Må bra.'],
    status: 'implemented',
    sectionId: 'wellbeing',
  },
  {
    id: 'more.senior',
    title: '65+',
    aliases: ['65', 'senior', 'vardag'],
    summary: '65+ · Min vardag samlar medicin, vardag, minnen och nöje.',
    steps: ['Öppna Mer.', 'Öppna 65+ · Min vardag.'],
    status: 'implemented',
    sectionId: 'senior-65-plus',
  },
  {
    id: 'more.economy',
    title: 'Ekonomi',
    aliases: ['ekonomi', 'budget', 'utgift', 'economy'],
    summary: 'Ekonomi samlar utgifter, budget, skulder och sparande. Det är inte appens abonnemang.',
    steps: ['Öppna Mer.', 'Öppna Ekonomi.'],
    status: 'implemented',
    sectionId: 'economy',
  },
  {
    id: 'more.inkasso',
    title: 'Inkasso',
    aliases: ['inkasso', 'krav', 'förfallodatum'],
    summary: 'Inkasso samlar krav, förfallodatum, betalningar och mer tid.',
    steps: ['Öppna Mer.', 'Öppna Inkasso.'],
    status: 'implemented',
    sectionId: 'inkasso',
  },
  {
    id: 'more.enforcement',
    title: 'Kronofogden',
    aliases: ['kronofogden', 'ärende'],
    summary: 'Kronofogden samlar ärenden, skulder, deadlines och en betalningsöversikt.',
    steps: ['Öppna Mer.', 'Öppna Kronofogden.'],
    status: 'implemented',
    sectionId: 'kronofogden',
  },
  {
    id: 'more.sign-language',
    title: 'Teckenspråk',
    aliases: ['teckenspråk', 'sts', 'sign language'],
    summary: 'Teckenspråk samlar STS, fraser och förberedelse för senare teckenstöd.',
    steps: ['Öppna Mer.', 'Öppna Teckenspråk.'],
    status: 'partial',
    sectionId: 'sign-language',
  },
  {
    id: 'more.animals',
    title: 'Djurvärlden',
    aliases: ['djur', 'insekter', 'animals'],
    summary: 'Djurvärlden samlar djur, insekter och faktagranskade videospår.',
    steps: ['Öppna Mer.', 'Öppna Djurvärlden.'],
    status: 'implemented',
    sectionId: 'animal-world',
  },
  {
    id: 'more.pregnancy',
    title: 'Graviditet och första året',
    aliases: ['graviditet', 'första året', 'pregnancy'],
    summary: 'Graviditet & första året samlar graviditet, första året och vårdhänvisningar.',
    steps: ['Öppna Mer.', 'Öppna Graviditet & första året.'],
    status: 'implemented',
    sectionId: 'pregnancy-first-year',
  },
  {
    id: 'more.accessibility',
    title: 'Tillgänglighet',
    aliases: ['tillgänglighet', 'hjälpmedel', 'accessibility'],
    summary: 'Tillgänglighet & hjälpmedel är en egen del i Mer. Mappen beskriver anpassningar. Flera stöd är markerade som senare funktioner.',
    steps: ['Öppna Mer.', 'Öppna Tillgänglighet & hjälpmedel.'],
    status: 'partial',
    sectionId: 'accessibility',
  },
  {
    id: 'more.backup',
    title: 'Säkerhet och backup',
    aliases: ['backup', 'moln', 'synk', 'återställ'],
    summary: 'Säkerhet & Backup samlar backup, återställning, synk och moln.',
    steps: ['Öppna Mer.', 'Öppna Säkerhet & Backup.'],
    status: 'implemented',
    sectionId: 'sakerhet-backup',
  },
  {
    id: 'more.import-export',
    title: 'Import och export',
    aliases: ['import', 'export', 'dataimport', 'dataexport'],
    summary: 'Import & Export samlar dataimport och dataexport.',
    steps: ['Öppna Mer.', 'Öppna Import & Export.'],
    status: 'implemented',
    sectionId: 'import-export',
  },
  {
    id: 'more.archive',
    title: 'Arkiv och historik',
    aliases: ['arkiv', 'historik', 'logg'],
    summary: 'Arkiv & Historik samlar backup-historik och loggar.',
    steps: ['Öppna Mer.', 'Öppna Arkiv & Historik.'],
    status: 'implemented',
    sectionId: 'arkiv-historik',
  },
  {
    id: 'settings.profile',
    title: 'Profil',
    aliases: ['profil', 'mina uppgifter', 'personuppgifter', 'uppgifter'],
    summary: 'Profilen med namn, mål, längd och aktivitet ändras med knappen Ändra profil. Knappen finns i Inställningar och i den övre raden på Hem.',
    steps: ['Öppna Mer.', 'Öppna Inställningar.', 'Tryck på Ändra profil.'],
    limits: 'AI-Hjälpen kan inte ändra profilen, kontot eller betalningen.',
    status: 'implemented',
    sectionId: 'installningar',
  },
  {
    id: 'more.settings',
    title: 'Inställningar',
    aliases: ['inställningar', 'settings'],
    summary: 'Inställningar samlar appinställningar, språk, abonnemang och enheter. AI-Hjälpen ligger här.',
    steps: ['Öppna Mer.', 'Öppna Inställningar.'],
    status: 'implemented',
    sectionId: 'installningar',
  },
  {
    id: 'settings.language',
    title: 'Språk',
    aliases: ['språk', 'language', 'locale', 'arabiska', 'kinesiska'],
    summary: 'Språket väljs i Inställningar. Samma val styr appens språk och språket som AI-Hjälpen svarar på.',
    steps: ['Öppna Mer.', 'Öppna Inställningar.', 'Välj språk i språklistan.'],
    status: 'implemented',
    sectionId: 'installningar',
  },
  {
    id: 'settings.plan',
    title: 'Abonnemang',
    aliases: ['abonnemang', 'pris', 'kostar', 'betalning', 'kvot', 'paket', 'plan', 'subscription', 'quota', 'uppsägning', 'avsluta'],
    summary: 'Inställningar visar abonnemang och användning. Priserna i plankatalogen är preliminära och ersätter inte verifierade kundfakta om plan, pris, kvot, betalning eller uppsägning. AI-Hjälpen kan inte ändra abonnemang, betalning eller uppsägning själv. En uppsägning kräver en separat bekräftelse. Kontoradering görs inte här.',
    steps: ['Öppna Mer.', 'Öppna Inställningar.', 'Läs abonnemang och jämför abonnemang där.'],
    status: 'partial',
    sectionId: 'installningar',
  },
  {
    id: 'settings.devices',
    title: 'Enheter',
    aliases: ['enhet', 'device', 'molnstatus'],
    summary: 'Inställningar visar den här enheten och om uppgifterna bara finns lokalt eller också i molnet.',
    steps: ['Öppna Mer.', 'Öppna Inställningar.', 'Läs avsnittet om appinställningar och enheter.'],
    status: 'implemented',
    sectionId: 'installningar',
  },
  {
    id: 'settings.remote-analysis',
    title: 'Fjärranalys',
    aliases: ['samtycke', 'fjärranalys', 'bildanalys', 'consent'],
    summary: 'Inställningar visar om samtycke till fjärranalys av bilder är givet och har en knapp som återkallar det samtycket.',
    steps: ['Öppna Mer.', 'Öppna Inställningar.', 'Använd knappen för att återkalla samtycke om det är givet.'],
    status: 'implemented',
    sectionId: 'installningar',
  },
]

const catalogIds = new Set(knowledgeCatalog.map((entry) => entry.id))

export function isKnowledgeId(id) {
  return catalogIds.has(id)
}

export function getKnowledgeEntry(id) {
  return knowledgeCatalog.find((entry) => entry.id === id) || null
}
