import { supabase } from '../../services/supabaseClient.js'
import { recordEncryptedPlaceHistoryPoint } from './placeHistoryService.js'
import { encryptPlacePayload, ensurePlaceE2eeIdentity } from './placeE2eeService.js'

let activeWatchId=null,activeVisibilityHandler=null,activeSharingState=null,lastActiveWriteAt=0,activeWriteInFlight=false
const positionFrequencyStorageKey='viktkollen.place.positionFrequency.v1'
const positionFrequencyIntervals=Object.freeze({live:5000,'10m':600000,'30m':1800000,'1h':3600000,battery:120000})
let activeSharingStatus={active:false,paused:false,lastUpdatedAt:null,accuracyMeters:null}
const activeSharingStatusListeners=new Set()
function notifyActiveSharingStatus(patch){activeSharingStatus={...activeSharingStatus,...patch};activeSharingStatusListeners.forEach(l=>l({...activeSharingStatus}))}
export function getActiveLocationSharingStatus(){return{...activeSharingStatus}}
export function subscribeActiveLocationSharingStatus(listener){if(typeof listener!=='function')return()=>{};activeSharingStatusListeners.add(listener);listener({...activeSharingStatus});return()=>activeSharingStatusListeners.delete(listener)}
export function getPlacePositionFrequency(){if(typeof window==='undefined')return'30m';const v=window.localStorage.getItem(positionFrequencyStorageKey);return Object.prototype.hasOwnProperty.call(positionFrequencyIntervals,v)?v:'30m'}
export function setPlacePositionFrequency(value){const n=Object.prototype.hasOwnProperty.call(positionFrequencyIntervals,value)?value:'30m';if(typeof window!=='undefined')window.localStorage.setItem(positionFrequencyStorageKey,n);if(activeSharingState)configureActiveLocationSharing(activeSharingState);return n}
function locationOptions({batterySaverEnabled=false}={}){return{enableHighAccuracy:!batterySaverEnabled,maximumAge:batterySaverEnabled?300000:30000,timeout:batterySaverEnabled?10000:15000}}
function getCurrentPosition({batterySaverEnabled=false}={}){return new Promise((resolve,reject)=>{if(typeof navigator==='undefined'||!navigator.geolocation){reject(new Error('Platsåtkomst stöds inte på den här enheten.'));return}navigator.geolocation.getCurrentPosition(resolve,reject,locationOptions({batterySaverEnabled}))})}
export function requestPlaceLocationPermission(){return getCurrentPosition()}
async function getSignedInUserId(){if(!supabase)return null;const{data,error}=await supabase.auth.getSession();if(error)throw error;return data?.session?.user?.id||null}
async function getPrimaryFamilyId(userId){const{data,error}=await supabase.from('place_family_members').select('family_id').eq('user_id',userId).order('joined_at',{ascending:true}).limit(1).maybeSingle();if(error)throw error;return data?.family_id||null}
async function disableRemoteSharing(userId,consentGrantedAt){const{error}=await supabase.from('place_location_shares').update({consent_granted_at:consentGrantedAt||null,sharing_enabled:false,latitude:null,longitude:null,accuracy_meters:null,location_recorded_at:null,encrypted_payload:null,encrypted_iv:null,recipient_user_id:null,updated_at:new Date().toISOString()}).eq('user_id',userId);if(error)throw error}
async function activeRecipient(userId,familyId){const{data,error}=await supabase.from('place_trip_shares').select('viewer_user_id').eq('owner_user_id',userId).eq('family_id',familyId).is('ended_at',null).order('started_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data?.viewer_user_id||null}
async function persistSharedPosition(state,position){if(!supabase)return{ok:false,reason:'supabase-unavailable'};const userId=await getSignedInUserId();if(!userId)return{ok:false,reason:'signed-out'};const familyId=await getPrimaryFamilyId(userId);if(!familyId)return{ok:false,reason:'no-family-membership'};await ensurePlaceE2eeIdentity();const recordedAt=position.timestamp?new Date(position.timestamp).toISOString():new Date().toISOString(),accuracyMeters=Number.isFinite(position.coords.accuracy)?position.coords.accuracy:null,consentGrantedAt=state?.consentGrantedAt||new Date().toISOString(),recipient=await activeRecipient(userId,familyId);let encrypted=null;if(recipient)encrypted=await encryptPlacePayload(recipient,{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy_meters:accuracyMeters,location_recorded_at:recordedAt});const row={user_id:userId,family_id:familyId,consent_granted_at:consentGrantedAt,sharing_enabled:true,latitude:null,longitude:null,accuracy_meters:null,location_recorded_at:recordedAt,encrypted_payload:encrypted?.encrypted_payload||null,encrypted_iv:encrypted?.encrypted_iv||null,recipient_user_id:recipient,updated_at:new Date().toISOString()};const{error}=await supabase.from('place_location_shares').upsert(row,{onConflict:'user_id'});if(error)throw error;notifyActiveSharingStatus({active:typeof document==='undefined'||document.visibilityState!=='hidden',paused:typeof document!=='undefined'&&document.visibilityState==='hidden',lastUpdatedAt:recordedAt,accuracyMeters});void recordEncryptedPlaceHistoryPoint({userId,familyId,latitude:position.coords.latitude,longitude:position.coords.longitude,accuracyMeters,recordedAt}).catch(e=>console.warn('Encrypted place history write failed:',e?.message||e));return{ok:true,sharingEnabled:true,recordedAt}}
export async function syncPlaceLocationSharing(state){if(!supabase)return{ok:false,reason:'supabase-unavailable'};const userId=await getSignedInUserId();if(!userId)return{ok:false,reason:'signed-out'};const consentGranted=Boolean(state?.consentGranted),sharingEnabled=Boolean(state?.sharingEnabled&&consentGranted),frequency=getPlacePositionFrequency(),batterySaverEnabled=Boolean(state?.batterySaverEnabled||frequency==='battery'),consentGrantedAt=consentGranted?state?.consentGrantedAt||new Date().toISOString():null;if(!sharingEnabled){notifyActiveSharingStatus({active:false,paused:false});await disableRemoteSharing(userId,consentGrantedAt);return{ok:true,sharingEnabled:false}}const position=await getCurrentPosition({batterySaverEnabled});return persistSharedPosition(state,position)}
export function stopActiveLocationSharing(){if(typeof navigator!=='undefined'&&navigator.geolocation&&activeWatchId!==null)navigator.geolocation.clearWatch(activeWatchId);if(typeof document!=='undefined'&&activeVisibilityHandler)document.removeEventListener('visibilitychange',activeVisibilityHandler);activeWatchId=null;activeVisibilityHandler=null;activeSharingState=null;lastActiveWriteAt=0;activeWriteInFlight=false}
export function configureActiveLocationSharing(state){stopActiveLocationSharing();const consentGranted=Boolean(state?.consentGranted),sharingEnabled=Boolean(state?.sharingEnabled&&consentGranted);if(!sharingEnabled){notifyActiveSharingStatus({active:false,paused:false});return{active:false,reason:'sharing-disabled'}}if(typeof navigator==='undefined'||!navigator.geolocation||typeof document==='undefined'){notifyActiveSharingStatus({active:false,paused:true});return{active:false,reason:'unsupported'}}activeSharingState=state;lastActiveWriteAt=0;const startWatch=()=>{if(!activeSharingState||activeWatchId!==null||document.visibilityState==='hidden')return;const frequency=getPlacePositionFrequency(),batterySaverEnabled=Boolean(activeSharingState?.batterySaverEnabled||frequency==='battery'),minWriteInterval=positionFrequencyIntervals[frequency]||positionFrequencyIntervals['30m'];activeWatchId=navigator.geolocation.watchPosition(position=>{const now=Date.now();if(activeWriteInFlight||now-lastActiveWriteAt<minWriteInterval)return;lastActiveWriteAt=now;activeWriteInFlight=true;void persistSharedPosition(activeSharingState,position).catch(e=>console.warn('Active place sharing update failed:',e?.message||e)).finally(()=>{activeWriteInFlight=false})},e=>console.warn('Active place sharing GPS unavailable:',e?.message||e),locationOptions({batterySaverEnabled}));notifyActiveSharingStatus({active:true,paused:false})};const stopWatch=()=>{if(activeWatchId===null)return;navigator.geolocation.clearWatch(activeWatchId);activeWatchId=null;notifyActiveSharingStatus({active:false,paused:true})};activeVisibilityHandler=()=>{if(document.visibilityState==='hidden'){stopWatch();return}lastActiveWriteAt=0;startWatch()};document.addEventListener('visibilitychange',activeVisibilityHandler);startWatch();return{active:activeWatchId!==null,reason:activeWatchId!==null?'watching':'hidden'}}
