import { supabase } from '../../services/supabaseClient.js'
import { ensurePlacePushSubscription } from './placePushService.js'
import { decryptEnvelope, writeFamilyEnvelopes } from './placeFamilyE2eeService.js'
function unavailable(message='Trygga platser kräver att du är inloggad.'){return{data:[],error:new Error(message)}}
async function getSessionUserId(){if(!supabase)return{userId:null,error:new Error('Supabase är inte anslutet.')};const{data,error}=await supabase.auth.getSession();return{userId:data?.session?.user?.id||null,error:error||null}}
async function getFamilyIds(userId){const{data,error}=await supabase.from('place_family_members').select('family_id').eq('user_id',userId);return{familyIds:[...new Set((data||[]).map(r=>r.family_id).filter(Boolean))],error:error||null}}
function currentPosition(){return new Promise((resolve,reject)=>{if(typeof navigator==='undefined'||!navigator.geolocation)return reject(new Error('Platsåtkomst stöds inte på den här enheten.'));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_meters:Number.isFinite(p.coords.accuracy)?p.coords.accuracy:null}),reject,{enableHighAccuracy:true,timeout:15000,maximumAge:30000})})}
function distanceMeters(a,b,c,d){const r=v=>v*Math.PI/180,R=6371000,x=r(c-a),y=r(d-b),q=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
export async function loadSafePlaces(){const{userId,error:sessionError}=await getSessionUserId();if(sessionError)return{data:[],error:sessionError};if(!userId)return unavailable();const{familyIds,error:membershipError}=await getFamilyIds(userId);if(membershipError)return{data:[],error:membershipError};if(!familyIds.length)return{data:[],error:null};const{data,error}=await supabase.from('place_safe_places').select('id,family_id,created_by,name,radius_meters,notify_on_arrival,notify_on_departure,created_at,updated_at').in('family_id',familyIds).order('created_at',{ascending:true});if(error)return{data:[],error};const out=[];for(const row of data||[]){let p=null;if(row.created_by!==userId){try{p=await decryptEnvelope('safe_place',row.id,row.created_by)}catch{}}out.push({...row,latitude:p?.latitude??null,longitude:p?.longitude??null})}return{data:out,error:null}}
export async function createSafePlaceFromOwnLatestLocation(name,radiusMeters=150){const safeName=String(name||'').trim();if(!safeName)return{data:null,error:new Error('Skriv ett namn på platsen.')};const{userId,error:sessionError}=await getSessionUserId();if(sessionError)return{data:null,error:sessionError};if(!userId)return{data:null,error:new Error('Du måste vara inloggad.')};const{familyIds,error:membershipError}=await getFamilyIds(userId);if(membershipError)return{data:null,error:membershipError};if(!familyIds.length)return{data:null,error:new Error('Ingen familj är ansluten.')};try{const pos=await currentPosition(),familyId=familyIds[0];const{data,error}=await supabase.from('place_safe_places').insert({family_id:familyId,created_by:userId,name:safeName,latitude:null,longitude:null,radius_meters:radiusMeters}).select('id,family_id,created_by,name,radius_meters,notify_on_arrival,notify_on_departure,created_at,updated_at').single();if(error)return{data:null,error};await writeFamilyEnvelopes('safe_place',data.id,familyId,{latitude:pos.latitude,longitude:pos.longitude});return{data:{...data,latitude:pos.latitude,longitude:pos.longitude},error:null}}catch(error){return{data:null,error}}}
export async function updateSafePlaceNotifications(id,updates){if(!supabase||!id)return{data:null,error:new Error('Platsnotisen kunde inte ändras.')};const patch={};if(typeof updates?.notifyOnArrival==='boolean')patch.notify_on_arrival=updates.notifyOnArrival;if(typeof updates?.notifyOnDeparture==='boolean')patch.notify_on_departure=updates.notifyOnDeparture;if(!Object.keys(patch).length)return{data:null,error:new Error('Ingen notisinställning valdes.')};const wantsPush=updates?.notifyOnArrival===true||updates?.notifyOnDeparture===true,pushSetup=wantsPush?ensurePlacePushSubscription().catch(pushError=>({data:null,error:pushError})):null;const{data,error}=await supabase.from('place_safe_places').update(patch).eq('id',id).select('id,family_id,created_by,name,radius_meters,notify_on_arrival,notify_on_departure,created_at,updated_at').single();const pushResult=pushSetup?await pushSetup:null;if(pushResult?.error)console.warn('Place push setup failed:',pushResult.error?.message||pushResult.error);return{data:data||null,error:error||null,pushEnabled:Boolean(pushResult?.data?.enabled),pushError:pushResult?.error||null}}
export function subscribeSafePlaceTransitions(safePlaces,onTransition){if(typeof onTransition!=='function'||typeof navigator==='undefined'||!navigator.geolocation)return()=>{};const active=(Array.isArray(safePlaces)?safePlaces:[]).filter(p=>(p?.notify_on_arrival||p?.notify_on_departure)&&Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude)));if(!active.length)return()=>{};const previous=new Map();const id=navigator.geolocation.watchPosition(pos=>{const lat=pos.coords.latitude,lon=pos.coords.longitude;for(const place of active){const inside=distanceMeters(lat,lon,Number(place.latitude),Number(place.longitude))<=Number(place.radius_meters||150),old=previous.get(place.id);previous.set(place.id,inside);if(old===undefined||old===inside)continue;if(inside&&place.notify_on_arrival)onTransition({type:'arrival',place,userId:null,location:{latitude:lat,longitude:lon}});else if(!inside&&place.notify_on_departure)onTransition({type:'departure',place,userId:null,location:{latitude:lat,longitude:lon}})}},e=>console.warn('Local safe-place GPS unavailable:',e?.message||e),{enableHighAccuracy:false,maximumAge:60000,timeout:15000});return()=>navigator.geolocation.clearWatch(id)}
export async function deleteSafePlace(id){if(!supabase||!id)return{error:new Error('Platsen kunde inte raderas.')};await supabase.from('place_e2ee_envelopes').delete().eq('resource_type','safe_place').eq('resource_id',id);const{error}=await supabase.from('place_safe_places').delete().eq('id',id);return{error:error||null}}
