import { supabase } from '../../services/supabaseClient.js'

const DB='viktkollen-place-e2ee-v1',STORE='keys',KEY='identity'
const enc=new TextEncoder(),dec=new TextDecoder()
function b64(bytes){let s='';new Uint8Array(bytes).forEach(v=>{s+=String.fromCharCode(v)});return btoa(s)}
function bytes(s){const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function stored(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()})}
async function save(v){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,KEY);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function identity(){let pair=await stored();if(pair)return pair;pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},false,['deriveKey','deriveBits']);await save(pair);return pair}
export async function ensurePlaceE2eeIdentity(){const {data}=await supabase.auth.getSession(),userId=data?.session?.user?.id;if(!userId)throw new Error('Du behöver vara inloggad.');const pair=await identity(),publicJwk=await crypto.subtle.exportKey('jwk',pair.publicKey);const {error}=await supabase.from('place_e2ee_public_keys').upsert({user_id:userId,public_jwk:publicJwk,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;return userId}
async function sharedKey(recipientUserId){const pair=await identity(),{data,error}=await supabase.from('place_e2ee_public_keys').select('public_jwk').eq('user_id',recipientUserId).maybeSingle();if(error)throw error;if(!data?.public_jwk)throw new Error('Mottagarens krypteringsnyckel saknas. Mottagaren behöver öppna Plats först.');const pub=await crypto.subtle.importKey('jwk',data.public_jwk,{name:'ECDH',namedCurve:'P-256'},false,[]);return crypto.subtle.deriveKey({name:'ECDH',public:pub},pair.privateKey,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
export async function encryptPlacePayload(recipientUserId,payload){await ensurePlaceE2eeIdentity();const key=await sharedKey(recipientUserId),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(payload)));return {encrypted_payload:b64(cipher),encrypted_iv:b64(iv),recipient_user_id:recipientUserId}}
export async function decryptPlacePayload(senderUserId,row){await ensurePlaceE2eeIdentity();const key=await sharedKey(senderUserId),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(row.encrypted_iv)},key,bytes(row.encrypted_payload));return JSON.parse(dec.decode(plain))}
