import { supabase } from '../../services/supabaseClient.js'

const DB='viktkollen-place-e2ee-v1',STORE='keys',KEY='identity',DEVICE_KEY='device-id'
const enc=new TextEncoder(),dec=new TextDecoder()
function b64(bytes){let s='';new Uint8Array(bytes).forEach(v=>{s+=String.fromCharCode(v)});return btoa(s)}
function bytes(s){const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function stored(key=KEY){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()})}
async function save(v,key=KEY){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,key);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function identity(){let pair=await stored();if(pair)return pair;pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},false,['deriveKey','deriveBits']);await save(pair);return pair}
async function deviceId(){let id=await stored(DEVICE_KEY);if(id)return id;id=crypto.randomUUID();await save(id,DEVICE_KEY);return id}
async function sessionUserId(){const{data,error}=await supabase.auth.getSession();if(error)throw error;const id=data?.session?.user?.id;if(!id)throw new Error('Du behöver vara inloggad.');return id}
export async function getPlaceE2eeDeviceId(){return deviceId()}
export async function ensurePlaceE2eeIdentity(){const userId=await sessionUserId(),pair=await identity(),id=await deviceId(),publicJwk=await crypto.subtle.exportKey('jwk',pair.publicKey);const{error}=await supabase.from('place_e2ee_device_keys').upsert({user_id:userId,device_id:id,public_jwk:publicJwk,updated_at:new Date().toISOString()},{onConflict:'user_id,device_id'});if(error)throw error;return userId}
export async function getPlaceE2eePublicKeys(userId){const{data,error}=await supabase.from('place_e2ee_device_keys').select('device_id,public_jwk').eq('user_id',userId);if(error)throw error;if(data?.length)return data;const{data:legacy,error:legacyError}=await supabase.from('place_e2ee_public_keys').select('public_jwk').eq('user_id',userId).maybeSingle();if(legacyError)throw legacyError;return legacy?.public_jwk?[{device_id:'legacy',public_jwk:legacy.public_jwk}]:[]}
async function sharedKey(publicJwk){const pair=await identity(),pub=await crypto.subtle.importKey('jwk',publicJwk,{name:'ECDH',namedCurve:'P-256'},false,[]);return crypto.subtle.deriveKey({name:'ECDH',public:pub},pair.privateKey,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptForKey(recipientUserId,target,payload){const key=await sharedKey(target.public_jwk),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(payload)));return{encrypted_payload:b64(cipher),encrypted_iv:b64(iv),recipient_user_id:recipientUserId,recipient_device_id:target.device_id,sender_device_id:await deviceId()}}
export async function encryptPlacePayloads(recipientUserId,payload){await ensurePlaceE2eeIdentity();const keys=await getPlaceE2eePublicKeys(recipientUserId);if(!keys.length)throw new Error('Mottagarens krypteringsnyckel saknas. Mottagaren behöver öppna Plats först.');return Promise.all(keys.map(k=>encryptForKey(recipientUserId,k,payload)))}
export async function encryptPlacePayload(recipientUserId,payload){const all=await encryptPlacePayloads(recipientUserId,payload);return all[0]}
export async function decryptPlacePayload(senderUserId,row){await ensurePlaceE2eeIdentity();const senderKeys=await getPlaceE2eePublicKeys(senderUserId),myId=await deviceId();if(row?.recipient_device_id&&row.recipient_device_id!==myId&&row.recipient_device_id!=='legacy')throw new Error('Krypteringen är avsedd för en annan enhet.');const ordered=[...senderKeys].sort((a,b)=>a.device_id===row?.sender_device_id?-1:b.device_id===row?.sender_device_id?1:0);let lastError=null;for(const sender of ordered){try{const key=await sharedKey(sender.public_jwk),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(row.encrypted_iv)},key,bytes(row.encrypted_payload));return JSON.parse(dec.decode(plain))}catch(e){lastError=e}}throw lastError||new Error('Krypterad platsdata kan inte öppnas på den här enheten.')}
