import { supabase } from '../../services/supabaseClient.js'
import { decryptEnvelope, writeFamilyEnvelopes } from './placeFamilyE2eeService.js'
const allowedReasons=new Set(['threatened','lost','injured','unsafe','pickup','other'])
function unavailable(message='Trygghetslarm kräver att du är inloggad.'){return{data:null,error:new Error(message)}}
async function getSessionUserId(){if(!supabase)return null;const{data,error}=await supabase.auth.getSession();if(error)throw error;return data?.session?.user?.id||null}
async function getPrimaryFamilyId(userId){const{data,error}=await supabase.from('place_family_members').select('family_id').eq('user_id',userId).order('joined_at',{ascending:true}).limit(1).maybeSingle();if(error)throw error;return data?.family_id||null}
async function currentPosition(){return new Promise(resolve=>{if(!navigator?.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_meters:Number.isFinite(p.coords.accuracy)?p.coords.accuracy:null}),()=>resolve(null),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})})}
export async function loadSafetyAlerts(){if(!supabase)return{data:[],error:new Error('Trygghetslarm är inte anslutet.')};try{const userId=await getSessionUserId();if(!userId)return{data:[],error:unavailable().error};const{data:memberships,error:membershipError}=await supabase.from('place_family_members').select('family_id').eq('user_id',userId);if(membershipError)return{data:[],error:membershipError};const familyIds=[...new Set((memberships||[]).map(r=>r.family_id).filter(Boolean))];if(!familyIds.length)return{data:[],error:null};const since=new Date(Date.now()-86400000).toISOString(),{data,error}=await supabase.from('place_safety_alerts').select('id,family_id,sender_user_id,reason,created_at').in('family_id',familyIds).gte('created_at',since).order('created_at',{ascending:false}).limit(20);if(error)return{data:[],error};const out=[];for(const row of data||[]){let p=null;try{p=await decryptEnvelope('safety_alert',row.id,row.sender_user_id)}catch{}out.push({...row,latitude:p?.latitude??null,longitude:p?.longitude??null,accuracy_meters:p?.accuracy_meters??null})}return{data:out,error:null}}catch(error){return{data:[],error}}}
export async function sendSafetyAlert(reason){if(!allowedReasons.has(reason))return unavailable('Ogiltig anledning för trygghetslarm.');if(!supabase)return unavailable('Trygghetslarm är inte anslutet.');try{const userId=await getSessionUserId();if(!userId)return unavailable();const familyId=await getPrimaryFamilyId(userId);if(!familyId)return unavailable('Kontot är inte kopplat till någon familj ännu.');const location=await currentPosition();const{data,error}=await supabase.from('place_safety_alerts').insert({family_id:familyId,sender_user_id:userId,reason,latitude:null,longitude:null,accuracy_meters:null}).select('id,family_id,sender_user_id,reason,created_at').single();if(error)return{data:null,error};if(location)await writeFamilyEnvelopes('safety_alert',data.id,familyId,location);return{data:{...data,...(location||{})},error:null}}catch(error){return{data:null,error}}}
export function subscribeSafetyAlerts(onAlert){if(!supabase||typeof onAlert!=='function')return()=>{};const channel=supabase.channel(`place-safety-alerts-${Math.random().toString(36).slice(2)}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'place_safety_alerts'},payload=>{if(payload?.new)onAlert(payload.new)}).subscribe();return()=>{supabase.removeChannel(channel)}}
