import { filterSafeDefinitions } from './achievementSafety.js'

export const achievementCategories = [
  'consistency',
  'nutrition',
  'activity',
  'checkIns',
  'weightProgress',
  'goals',
  'habits',
  'coaching',
  'planning',
  'dataQuality',
  'appMilestones',
]

export const achievementDefinitions = [
  {
    category: 'checkIns',
    description: 'Första check-in registrerad.',
    id: 'first-check-in',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första check-in',
    unit: 'check-in',
    xp: 20,
  },
  {
    category: 'consistency',
    description: 'Tre dagar med registrerad data.',
    id: 'three-registered-days',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: 'Tre registrerade dagar',
    unit: 'dagar',
    xp: 30,
  },
  {
    category: 'consistency',
    description: 'Sju dagar med registrerad data, utan krav på obruten streak.',
    id: 'seven-registered-days',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 7,
    title: 'Sju registrerade dagar',
    unit: 'dagar',
    xp: 60,
  },
  {
    category: 'nutrition',
    description: 'Första faktiska måltiden loggad.',
    id: 'first-meal',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första måltiden',
    unit: 'måltid',
    xp: 20,
  },
  {
    category: 'nutrition',
    description: 'Sju faktiska måltider loggade.',
    id: 'seven-actual-meals',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 7,
    title: 'Sju måltider loggade',
    unit: 'måltider',
    xp: 40,
  },
  {
    category: 'activity',
    description: 'Första träningspasset eller aktivitet registrerad.',
    id: 'first-workout',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första aktiviteten',
    unit: 'aktivitet',
    xp: 20,
  },
  {
    category: 'activity',
    description: 'Steg registrerade under flera dagar.',
    id: 'three-step-days',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: 'Tre dagar med stegdata',
    unit: 'dagar',
    xp: 30,
  },
  {
    category: 'goals',
    description: 'Första målet skapat.',
    id: 'first-goal-created',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första målet',
    unit: 'mål',
    xp: 20,
  },
  {
    category: 'goals',
    description: 'Första målet slutfört explicit.',
    id: 'first-goal-completed',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första slutförda målet',
    unit: 'mål',
    xp: 50,
  },
  {
    category: 'habits',
    description: 'Första vanan skapad.',
    id: 'first-habit-created',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första vanan',
    unit: 'vana',
    xp: 20,
  },
  {
    category: 'habits',
    description: 'Vana följd flera dagar.',
    id: 'habit-three-days',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: 'Vana följd tre dagar',
    unit: 'dagar',
    xp: 35,
  },
  {
    category: 'planning',
    description: 'Ett veckofokus slutfört.',
    id: 'weekly-focus-completed',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Veckofokus slutfört',
    unit: 'fokus',
    xp: 50,
  },
  {
    category: 'coaching',
    description: 'Första coach action accepterad.',
    id: 'coach-action-accepted',
    source: 'adaptiveCoachFeedback',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Coach action accepterad',
    unit: 'action',
    xp: 25,
  },
  {
    category: 'coaching',
    description: 'Första coach action markerad klar.',
    id: 'coach-action-completed',
    source: 'adaptiveCoachFeedback',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Coach action klar',
    unit: 'action',
    xp: 45,
  },
  {
    category: 'dataQuality',
    description: 'Verifierad export, import eller backup händelse finns.',
    id: 'first-portability-event',
    source: 'repository',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Säker dataportabilitet',
    unit: 'händelse',
    xp: 25,
  },
]

export function getSafeAchievementDefinitions() {
  return filterSafeDefinitions(achievementDefinitions)
}
