import { filterSafeDefinitions } from './achievementSafety.js'

export const achievementCategories = [
  'consistency',
  'nutrition',
  'activity',
  'checkIns',
  'weightProgress',
  'goals',
  'habits',
  'coaching',
  'planning',
  'dataQuality',
  'appMilestones',
]

export const achievementDefinitions = [
  {
    category: 'weightProgress',
    description: 'Första invägningen registrerad.',
    id: 'first-weigh-in',
    source: 'weights',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första invägningen',
    unit: 'invägning',
    xp: 20,
  },
  {
    category: 'weightProgress',
    description: 'Ett kilo framsteg från startvikten mot målet.',
    id: 'weight-progress-1kg',
    source: 'weights',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: '1 kg framsteg',
    unit: 'kg',
    xp: 35,
  },
  {
    category: 'weightProgress',
    description: 'Tre kilo framsteg från startvikten mot målet.',
    id: 'weight-progress-3kg',
    source: 'weights',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: '3 kg framsteg',
    unit: 'kg',
    xp: 55,
  },
  {
    category: 'weightProgress',
    description: 'Fem kilo framsteg från startvikten mot målet.',
    id: 'weight-progress-5kg',
    source: 'weights',
    safetyCategory: 'safe_motivation',
    target: 5,
    title: '5 kg framsteg',
    unit: 'kg',
    xp: 75,
  },
  {
    category: 'weightProgress',
    description: 'Minst halvvägs mot målvikt.',
    id: 'halfway-goal-weight',
    source: 'weights',
    safetyCategory: 'safe_motivation',
    target: 50,
    title: 'Halvvägs till målvikt',
    unit: '%',
    xp: 70,
  },
  {
    category: 'weightProgress',
    description: 'Målvikten är nådd enligt viktmodellen.',
    id: 'goal-weight-reached',
    source: 'weights',
    safetyCategory: 'safe_motivation',
    target: 100,
    title: 'Målvikt nådd',
    unit: '%',
    xp: 90,
  },
  {
    category: 'checkIns',
    description: 'Första check-in registrerad.',
    id: 'first-check-in',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första check-in',
    unit: 'check-in',
    xp: 20,
  },
  {
    category: 'consistency',
    description: 'Tre dagar med registrerad data.',
    id: 'three-registered-days',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: 'Tre registrerade dagar',
    unit: 'dagar',
    xp: 30,
  },
  {
    category: 'consistency',
    description: 'Sju dagar med registrerad data, utan krav på obruten streak.',
    id: 'seven-registered-days',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 7,
    title: 'Sju registrerade dagar',
    unit: 'dagar',
    xp: 60,
  },
  {
    category: 'consistency',
    description: 'Tre dagar i rad med registrerad data.',
    id: 'consistency-3-day-streak',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: '3 dagar i rad',
    unit: 'dagar',
    xp: 35,
  },
  {
    category: 'consistency',
    description: 'Sju dagar i rad med registrerad data.',
    id: 'consistency-7-day-streak',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 7,
    title: '7 dagar i rad',
    unit: 'dagar',
    xp: 60,
  },
  {
    category: 'consistency',
    description: 'Fjorton dagar i rad med registrerad data.',
    id: 'consistency-14-day-streak',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 14,
    title: '14 dagar i rad',
    unit: 'dagar',
    xp: 80,
  },
  {
    category: 'consistency',
    description: 'Trettio dagar i rad med registrerad data.',
    id: 'consistency-30-day-streak',
    source: 'healthSnapshot',
    safetyCategory: 'safe_motivation',
    target: 30,
    title: '30 dagar i rad',
    unit: 'dagar',
    xp: 100,
  },
  {
    category: 'nutrition',
    description: 'Första faktiska måltiden loggad.',
    id: 'first-meal',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första måltiden',
    unit: 'måltid',
    xp: 20,
  },
  {
    category: 'nutrition',
    description: 'Proteinmålet nått första gången.',
    id: 'protein-goal-first',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Proteinmålet nått',
    unit: 'dag',
    xp: 35,
  },
  {
    category: 'nutrition',
    description: 'Proteinmålet nått fem dagar.',
    id: 'protein-goal-5-days',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 5,
    title: '5 proteindagar',
    unit: 'dagar',
    xp: 55,
  },
  {
    category: 'nutrition',
    description: 'Proteinmålet nått tio dagar.',
    id: 'protein-goal-10-days',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 10,
    title: '10 proteindagar',
    unit: 'dagar',
    xp: 75,
  },
  {
    category: 'nutrition',
    description: 'Proteinmålet nått tjugofem dagar.',
    id: 'protein-goal-25-days',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 25,
    title: '25 proteindagar',
    unit: 'dagar',
    xp: 100,
  },
  {
    category: 'nutrition',
    description: 'Tio faktiska måltider loggade.',
    id: 'ten-actual-meals',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 10,
    title: '10 måltider loggade',
    unit: 'måltider',
    xp: 60,
  },
  {
    category: 'nutrition',
    description: 'Femtio faktiska måltider loggade.',
    id: 'fifty-actual-meals',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 50,
    title: '50 måltider loggade',
    unit: 'måltider',
    xp: 100,
  },
  {
    category: 'nutrition',
    description: 'Sju faktiska måltider loggade.',
    id: 'seven-actual-meals',
    source: 'meals',
    safetyCategory: 'safe_motivation',
    target: 7,
    title: 'Sju måltider loggade',
    unit: 'måltider',
    xp: 40,
  },
  {
    category: 'activity',
    description: 'Minst 10 000 steg registrerade på en dag.',
    id: 'steps-10000-day',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 10000,
    title: '10 000 steg på en dag',
    unit: 'steg',
    xp: 45,
  },
  {
    category: 'activity',
    description: 'Totalt 50 000 steg registrerade.',
    id: 'steps-50000-total',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 50000,
    title: '50 000 steg totalt',
    unit: 'steg',
    xp: 60,
  },
  {
    category: 'activity',
    description: 'Totalt 100 000 steg registrerade.',
    id: 'steps-100000-total',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 100000,
    title: '100 000 steg totalt',
    unit: 'steg',
    xp: 80,
  },
  {
    category: 'activity',
    description: 'Totalt 250 000 steg registrerade.',
    id: 'steps-250000-total',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 250000,
    title: '250 000 steg totalt',
    unit: 'steg',
    xp: 100,
  },
  {
    category: 'activity',
    description: 'Första träningspasset eller aktivitet registrerad.',
    id: 'first-workout',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första aktiviteten',
    unit: 'aktivitet',
    xp: 20,
  },
  {
    category: 'activity',
    description: 'Steg registrerade under flera dagar.',
    id: 'three-step-days',
    source: 'checkIns',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: 'Tre dagar med stegdata',
    unit: 'dagar',
    xp: 30,
  },
  {
    category: 'goals',
    description: 'Första målet skapat.',
    id: 'first-goal-created',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första målet',
    unit: 'mål',
    xp: 20,
  },
  {
    category: 'goals',
    description: 'Första målet slutfört explicit.',
    id: 'first-goal-completed',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första slutförda målet',
    unit: 'mål',
    xp: 50,
  },
  {
    category: 'habits',
    description: 'Första vanan skapad.',
    id: 'first-habit-created',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Första vanan',
    unit: 'vana',
    xp: 20,
  },
  {
    category: 'habits',
    description: 'Vana följd flera dagar.',
    id: 'habit-three-days',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 3,
    title: 'Vana följd tre dagar',
    unit: 'dagar',
    xp: 35,
  },
  {
    category: 'planning',
    description: 'Ett veckofokus slutfört.',
    id: 'weekly-focus-completed',
    source: 'goalsHabits',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Veckofokus slutfört',
    unit: 'fokus',
    xp: 50,
  },
  {
    category: 'coaching',
    description: 'Första coach action accepterad.',
    id: 'coach-action-accepted',
    source: 'adaptiveCoachFeedback',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Coach action accepterad',
    unit: 'action',
    xp: 25,
  },
  {
    category: 'coaching',
    description: 'Första coach action markerad klar.',
    id: 'coach-action-completed',
    source: 'adaptiveCoachFeedback',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Coach action klar',
    unit: 'action',
    xp: 45,
  },
  {
    category: 'dataQuality',
    description: 'Verifierad export, import eller backup händelse finns.',
    id: 'first-portability-event',
    source: 'repository',
    safetyCategory: 'safe_motivation',
    target: 1,
    title: 'Säker dataportabilitet',
    unit: 'händelse',
    xp: 25,
  },
]

export function getSafeAchievementDefinitions() {
  return filterSafeDefinitions(achievementDefinitions)
}
