import { useEffect, useMemo, useRef, useState } from 'react'
import { displayNameForUser } from '../../features/place/placeFamilyMemberService.js'
import { loadFamilyLatestLocations } from '../../features/place/placeFamilyMapService.js'
import { loadOwnPlaceHistory } from '../../features/place/placeHistoryService.js'
import { loadSafePlaces } from '../../features/place/placeSafePlacesService.js'
import { supabase } from '../../services/supabaseClient.js'
import TripSharePanel from './TripSharePanel.jsx'
import './SchoolCardEnhancer.js'
import './FamilyMapView.css'

const positionFrequencyOptions = [['live','Live'],['10m','10 min'],['30m','30 min'],['1h','1 timme'],['battery','Batterispar']]
const historyPeriods = [['today','Idag'],['yesterday','Igår'],['7d','7 dagar'],['30d','30 dagar']]
function locationKey(l){return `${l.family_id}:${l.user_id}`}
function distanceMeters(a,b,c,d){const r=6371000,rad=(v)=>v*Math.PI/180,x=rad(c-a),y=rad(d-b),q=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return r*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function distanceLabel(m){if(!Number.isFinite(m))return null;return m<1000?`${Math.round(m)} m från Hem`:`${(m/1000).toLocaleString('sv-SE',{minimumFractionDigits:1,maximumFractionDigits:1})} km från Hem`}
function mapUrlForLocation(l){const a=Number(l.latitude),o=Number(l.longitude),p=.006,q=Math.max(.008,p/Math.max(Math.cos(a*Math.PI/180),.35)),s=new URLSearchParams({bbox:[o-q,a-p,o+q,a+p].join(','),layer:'mapnik',marker:`${a},${o}`});return `https://www.openstreetmap.org/export/embed.html?${s}`}
function relativeUpdatedAt(v){if(!v)return'okänd tid';const a=Math.max(0,Math.round((Date.now()-new Date(v).getTime())/1000));if(!Number.isFinite(a))return'okänd tid';if(a<60)return'nu';if(a<3600)return`${Math.floor(a/60)} min sedan`;if(a<86400)return`${Math.floor(a/3600)} tim sedan`;return new Date(v).toLocaleString()}
function historyPointDate(p){return new Date(p.recordedAt||p.created_at)}
function pointInPeriod(p,period){const d=historyPointDate(p);if(Number.isNaN(d.getTime()))return false;const n=new Date(),t=new Date(n.getFullYear(),n.getMonth(),n.getDate()),y=new Date(t);y.setDate(y.getDate()-1);if(period==='today')return d>=t;if(period==='yesterday')return d>=y&&d<t;return d>=new Date(n.getTime()-(period==='30d'?30:7)*86400000)}
function movementFromSamples(previous,current){if(!previous||!current)return null;const t1=new Date(previous.location_recorded_at).getTime(),t2=new Date(current.location_recorded_at).getTime(),seconds=(t2-t1)/1000;if(!Number.isFinite(seconds)||seconds<2||seconds>600)return null;const meters=distanceMeters(Number(previous.latitude),Number(previous.longitude),Number(current.latitude),Number(current.longitude));const accuracy=Math.max(Number(previous.accuracy_meters)||0,Number(current.accuracy_meters)||0);if(meters<=Math.max(20,accuracy))return {icon:'📍',label:'Stillastående',speed:null};const kmh=meters/seconds*3.6;if(kmh<1.5)return {icon:'📍',label:'Stillastående',speed:kmh};if(kmh<8)return {icon:'🚶',label:'Går',speed:kmh};if(kmh<25)return {icon:'🚲',label:'Cyklar / rör sig snabbt',speed:kmh};if(kmh<55)return {icon:'🚌',label:'Troligen buss eller bil',speed:kmh};if(kmh<110)return {icon:'🚗',label:'Troligen bil eller buss',speed:kmh};if(kmh<200)return {icon:'🚆',label:'Troligen tåg eller snabbt fordon',speed:kmh};return {icon:'✈️',label:'Snabb förflyttning',speed:kmh}}
function anomalyFromSamples(samples){if(!Array.isArray(samples)||samples.length<5)return null;const speeds=samples.map(s=>s?.speed).filter(Number.isFinite);if(speeds.length<5)return null;const latest=speeds[speeds.length-1],baseline=speeds.slice(0,-1).sort((a,b)=>a-b),median=baseline[Math.floor(baseline.length/2)];if(median<8&&latest>55)return 'Rörelsen skiljer sig tydligt från de senaste GPS-mätningarna.';if(median<25&&latest>110)return 'Ovanligt snabb förflyttning jämfört med de senaste GPS-mätningarna.';return null}

function FamilyMapView({locations,familyMembers}){
 const [liveLocations,setLiveLocations]=useState(locations||[]),[selectedKey,setSelectedKey]=useState(()=>locations?.[0]?locationKey(locations[0]):''),[positionFrequency,setPositionFrequency]=useState('30m'),[cardNotice,setCardNotice]=useState(''),[historyOpen,setHistoryOpen]=useState(false),[historyPeriod,setHistoryPeriod]=useState('today'),[history,setHistory]=useState([]),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState(''),[followLive,setFollowLive]=useState(false),[liveError,setLiveError]=useState(''),[homePlace,setHomePlace]=useState(null),[movementByUser,setMovementByUser]=useState({}),[anomalyByUser,setAnomalyByUser]=useState({});const previousLocationsRef=useRef(new Map()),movementSamplesRef=useRef(new Map())
 useEffect(()=>{if(!followLive)setLiveLocations(locations||[])},[locations,followLive])
 useEffect(()=>{let c=false;loadSafePlaces().then(r=>{if(c||r.error)return;setHomePlace((r.data||[]).find(p=>String(p.name||'').trim().toLocaleLowerCase('sv-SE')==='hem')||null)}).catch(()=>{});return()=>{c=true}},[])
 const validLocations=useMemo(()=>{const s=new Set();return(liveLocations||[]).filter(l=>{if(!Number.isFinite(Number(l.latitude))||!Number.isFinite(Number(l.longitude)))return false;const k=locationKey(l);if(s.has(k))return false;s.add(k);return true})},[liveLocations])
 const entries=useMemo(()=>{const b=validLocations.map(l=>l.display_name||displayNameForUser(familyMembers,l.user_id)),tot=b.reduce((c,n)=>({...c,[n]:(c[n]||0)+1}),{}),seen={};return validLocations.map((location,i)=>{const n=b[i];seen[n]=(seen[n]||0)+1;return{location,key:locationKey(location),label:tot[n]>1?`${n} ${seen[n]}`:n}})},[familyMembers,validLocations])
 useEffect(()=>{if(!entries.length){setSelectedKey('');return}if(!entries.some(e=>e.key===selectedKey))setSelectedKey(entries[0].key)},[entries,selectedKey])
 useEffect(()=>{if(!followLive)return undefined;let cancelled=false,busy=false;async function refresh(){if(busy)return;busy=true;try{const r=await loadFamilyLatestLocations();if(cancelled)return;if(r.error)setLiveError(r.error.message||'Livepositionen kunde inte uppdateras.');else{const next=Array.isArray(r.data)?r.data:[];setMovementByUser(current=>{const updated={...current},anomalies={};next.forEach(l=>{const key=locationKey(l),previous=previousLocationsRef.current.get(key);if(previous?.location_recorded_at!==l.location_recorded_at){const movement=movementFromSamples(previous,l);if(movement){updated[key]=movement;const samples=[...(movementSamplesRef.current.get(key)||[]),movement].slice(-8);movementSamplesRef.current.set(key,samples);anomalies[key]=anomalyFromSamples(samples)}previousLocationsRef.current.set(key,l)}});setAnomalyByUser(old=>({...old,...anomalies}));return updated});setLiveLocations(next);setLiveError('')}}catch(e){if(!cancelled)setLiveError(e?.message||'Livepositionen kunde inte uppdateras.')}finally{busy=false}}refresh();const timer=window.setInterval(refresh,5000);return()=>{cancelled=true;window.clearInterval(timer)}},[followLive])
 if(!entries.length)return null
 const selectedEntry=entries.find(e=>e.key===selectedKey)||entries[0],l=selectedEntry.location,updatedLabel=relativeUpdatedAt(l.location_recorded_at),isLive=l.location_recorded_at?Date.now()-new Date(l.location_recorded_at).getTime()<120000:false,visibleHistory=history.filter(p=>!p.locked&&pointInPeriod(p,historyPeriod)),homeDistance=homePlace&&homePlace.family_id===l.family_id?distanceMeters(Number(l.latitude),Number(l.longitude),Number(homePlace.latitude),Number(homePlace.longitude)):null,homeDistanceText=distanceLabel(homeDistance),movement=movementByUser[selectedEntry.key],anomaly=anomalyByUser[selectedEntry.key]
 async function openHistory(){setCardNotice('');setHistoryOpen(true);setHistoryLoading(true);setHistoryError('');try{const s=await supabase?.auth.getSession(),uid=s?.data?.session?.user?.id||null;if(!uid||l.user_id!==uid){setHistory([]);setHistoryError('Familjemedlemmens historik delas inte ännu. Endast din egen krypterade historik kan visas säkert.');return}const r=await loadOwnPlaceHistory();setHistory(Array.isArray(r.data)?r.data:[]);setHistoryError(r.error?.message||'')}catch(e){setHistory([]);setHistoryError(e?.message||'Historiken kunde inte hämtas.')}finally{setHistoryLoading(false)}}
 function toggleFollowLive(){setHistoryOpen(false);setCardNotice('');setLiveError('');if(!followLive){previousLocationsRef.current=new Map(validLocations.map(x=>[locationKey(x),x]));movementSamplesRef.current=new Map();setAnomalyByUser({})}setFollowLive(c=>!c)}
 return <div className={`family-map-view${followLive?' is-following-live':''}`}>
 {entries.length>1?<div className="family-map-person-switcher" aria-label="Välj familjemedlem på kartan">{entries.map(e=><button key={e.key} type="button" aria-pressed={e.key===selectedEntry.key} onClick={()=>{setSelectedKey(e.key);setHistoryOpen(false);setCardNotice('')}}>📍 {e.label}</button>)}</div>:null}
 {followLive?<div className="family-map-live-bar"><strong>🟢 Följer live · {selectedEntry.label}</strong><span>Uppdaterar var 5:e sekund medan kartan är öppen</span></div>:null}
 <div className="family-map-frame"><iframe key={`${selectedEntry.key}:${l.location_recorded_at||''}`} title={`Karta – ${selectedEntry.label}`} src={mapUrlForLocation(l)} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div>{liveError?<p className="family-map-card-notice" role="alert">{liveError}</p>:null}
 <article className="family-map-person-card" aria-live="polite"><div className="family-map-person-card-heading"><strong>{selectedEntry.label}</strong><span className={isLive?'is-live':''}>{isLive?'🟢 LIVE':'Senaste position'}</span></div><p>{movement?`${movement.icon} ${movement.label}`:'📍 Rörelse okänd'}</p>{movement?.speed!=null?<small>Beräknad fart cirka {Math.round(movement.speed)} km/h · transporttypen är en uppskattning från GPS-rörelsen</small>:null}{anomaly?<p className="family-map-card-notice">⚠️ {anomaly} Detta är en observation, inte ett larm.</p>:null}{homeDistanceText?<p>🏠 {homeDistanceText}</p>:<small>Spara en trygg plats med namnet Hem för att visa avstånd hem.</small>}<small>Senast uppdaterad: {updatedLabel}</small>{l.accuracy_meters!=null?<small>Noggrannhet ±{Math.round(l.accuracy_meters)} m</small>:null}<div className="family-map-person-actions"><button type="button" aria-pressed={followLive} onClick={toggleFollowLive}>{followLive?'Sluta följa':'Följ live'}</button><button type="button" onClick={()=>setCardNotice('Prata kopplas in när röstfunktionen är klar.')}>Prata</button><button type="button" onClick={openHistory}>Historik</button></div><label className="family-map-frequency"><span>Positionsfrekvens</span><select value={positionFrequency} onChange={e=>setPositionFrequency(e.target.value)}>{positionFrequencyOptions.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>{cardNotice?<p className="family-map-card-notice" role="status">{cardNotice}</p>:null}</article>
 <TripSharePanel familyMembers={familyMembers} />
 {historyOpen?<section className="family-map-history" aria-label={`Historik – ${selectedEntry.label}`}><div className="family-map-history-heading"><strong>Historik · {selectedEntry.label}</strong><button type="button" onClick={()=>setHistoryOpen(false)}>Stäng</button></div><div className="family-map-history-periods">{historyPeriods.map(([v,n])=><button key={v} type="button" aria-pressed={historyPeriod===v} onClick={()=>setHistoryPeriod(v)}>{n}</button>)}</div>{historyLoading?<p>Hämtar historik…</p>:null}{historyError?<p className="family-map-card-notice" role="status">{historyError}</p>:null}{!historyLoading&&!historyError&&visibleHistory.length===0?<p>Ingen sparad position under perioden.</p>:null}{visibleHistory.length?<div className="family-map-history-list">{visibleHistory.map(p=><article key={p.id}><strong>{historyPointDate(p).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><span>📍 {Number(p.latitude).toFixed(5)}, {Number(p.longitude).toFixed(5)}</span>{p.accuracyMeters!=null?<small>±{Math.round(p.accuracyMeters)} m</small>:null}</article>)}</div>:null}</section>:null}
 <div className="family-map-selected"><strong>Position</strong><span>{Number(l.latitude).toFixed(5)}, {Number(l.longitude).toFixed(5)}</span></div><p className="family-map-provider-note"><small>Kartan visas av OpenStreetMap. Endast området runt den valda delade positionen begärs när kartan öppnas.</small></p></div>
}
export default FamilyMapView