import { useEffect, useMemo, useState } from 'react'
import { displayNameForUser } from '../../features/place/placeFamilyMemberService.js'
import { loadFamilyLatestLocations } from '../../features/place/placeFamilyMapService.js'
import { loadOwnPlaceHistory } from '../../features/place/placeHistoryService.js'
import { loadSafePlaces } from '../../features/place/placeSafePlacesService.js'
import { supabase } from '../../services/supabaseClient.js'
import './SchoolCardEnhancer.js'
import './FamilyMapView.css'

const positionFrequencyOptions = [['live', 'Live'], ['10m', '10 min'], ['30m', '30 min'], ['1h', '1 timme'], ['battery', 'Batterispar']]
const historyPeriods = [['today', 'Idag'], ['yesterday', 'Igår'], ['7d', '7 dagar'], ['30d', '30 dagar']]
function locationKey(location) { return `${location.family_id}:${location.user_id}` }
function distanceMeters(lat1, lon1, lat2, lon2) { const r = 6371000; const rad = (v) => v * Math.PI / 180; const dLat = rad(lat2-lat1); const dLon = rad(lon2-lon1); const a = Math.sin(dLat/2)**2 + Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLon/2)**2; return r * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)) }
function distanceLabel(meters) { if (!Number.isFinite(meters)) return null; return meters < 1000 ? `${Math.round(meters)} m från Hem` : `${(meters/1000).toLocaleString('sv-SE',{minimumFractionDigits:1,maximumFractionDigits:1})} km från Hem` }
function mapUrlForLocation(location) { const latitude=Number(location.latitude), longitude=Number(location.longitude), latitudePadding=.006, longitudePadding=Math.max(.008,latitudePadding/Math.max(Math.cos(latitude*Math.PI/180),.35)); const params=new URLSearchParams({bbox:[longitude-longitudePadding,latitude-latitudePadding,longitude+longitudePadding,latitude+latitudePadding].join(','),layer:'mapnik',marker:`${latitude},${longitude}`}); return `https://www.openstreetmap.org/export/embed.html?${params.toString()}` }
function relativeUpdatedAt(value) { if(!value)return'okänd tid'; const age=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000)); if(!Number.isFinite(age))return'okänd tid'; if(age<60)return'nu'; if(age<3600)return`${Math.floor(age/60)} min sedan`; if(age<86400)return`${Math.floor(age/3600)} tim sedan`; return new Date(value).toLocaleString() }
function historyPointDate(point){return new Date(point.recordedAt||point.created_at)}
function pointInPeriod(point,period){const date=historyPointDate(point);if(Number.isNaN(date.getTime()))return false;const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),yesterday=new Date(today);yesterday.setDate(yesterday.getDate()-1);if(period==='today')return date>=today;if(period==='yesterday')return date>=yesterday&&date<today;return date>=new Date(now.getTime()-(period==='30d'?30:7)*86400000)}

function FamilyMapView({ locations, familyMembers }) {
 const [liveLocations,setLiveLocations]=useState(locations||[]),[selectedKey,setSelectedKey]=useState(()=>locations?.[0]?locationKey(locations[0]):''),[positionFrequency,setPositionFrequency]=useState('30m'),[cardNotice,setCardNotice]=useState(''),[historyOpen,setHistoryOpen]=useState(false),[historyPeriod,setHistoryPeriod]=useState('today'),[history,setHistory]=useState([]),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState(''),[followLive,setFollowLive]=useState(false),[liveError,setLiveError]=useState(''),[homePlace,setHomePlace]=useState(null)
 useEffect(()=>{if(!followLive)setLiveLocations(locations||[])},[locations,followLive])
 useEffect(()=>{let cancelled=false;loadSafePlaces().then((result)=>{if(cancelled||result.error)return;const home=(result.data||[]).find((place)=>String(place.name||'').trim().toLocaleLowerCase('sv-SE')==='hem');setHomePlace(home||null)}).catch(()=>{});return()=>{cancelled=true}},[])
 const validLocations=useMemo(()=>{const seen=new Set();return(liveLocations||[]).filter((location)=>{if(!Number.isFinite(Number(location.latitude))||!Number.isFinite(Number(location.longitude)))return false;const key=locationKey(location);if(seen.has(key))return false;seen.add(key);return true})},[liveLocations])
 const entries=useMemo(()=>{const baseNames=validLocations.map((l)=>l.display_name||displayNameForUser(familyMembers,l.user_id)),totals=baseNames.reduce((c,n)=>({...c,[n]:(c[n]||0)+1}),{}),seen={};return validLocations.map((location,index)=>{const baseName=baseNames[index];seen[baseName]=(seen[baseName]||0)+1;return{location,key:locationKey(location),label:totals[baseName]>1?`${baseName} ${seen[baseName]}`:baseName}})},[familyMembers,validLocations])
 useEffect(()=>{if(!entries.length){setSelectedKey('');return}if(!entries.some((e)=>e.key===selectedKey))setSelectedKey(entries[0].key)},[entries,selectedKey])
 useEffect(()=>{if(!followLive)return undefined;let cancelled=false,busy=false;async function refresh(){if(busy)return;busy=true;try{const result=await loadFamilyLatestLocations();if(cancelled)return;if(result.error)setLiveError(result.error.message||'Livepositionen kunde inte uppdateras.');else{setLiveLocations(Array.isArray(result.data)?result.data:[]);setLiveError('')}}catch(error){if(!cancelled)setLiveError(error?.message||'Livepositionen kunde inte uppdateras.')}finally{busy=false}}refresh();const timer=window.setInterval(refresh,5000);return()=>{cancelled=true;window.clearInterval(timer)}},[followLive])
 if(!entries.length)return null
 const selectedEntry=entries.find((e)=>e.key===selectedKey)||entries[0],selectedLocation=selectedEntry.location,updatedLabel=relativeUpdatedAt(selectedLocation.location_recorded_at),isLive=selectedLocation.location_recorded_at?Date.now()-new Date(selectedLocation.location_recorded_at).getTime()<120000:false,visibleHistory=history.filter((p)=>!p.locked&&pointInPeriod(p,historyPeriod));const homeDistance=homePlace&&homePlace.family_id===selectedLocation.family_id?distanceMeters(Number(selectedLocation.latitude),Number(selectedLocation.longitude),Number(homePlace.latitude),Number(homePlace.longitude)):null,homeDistanceText=distanceLabel(homeDistance)
 async function openHistory(){setCardNotice('');setHistoryOpen(true);setHistoryLoading(true);setHistoryError('');try{const sessionResult=await supabase?.auth.getSession(),ownUserId=sessionResult?.data?.session?.user?.id||null;if(!ownUserId||selectedLocation.user_id!==ownUserId){setHistory([]);setHistoryError('Familjemedlemmens historik delas inte ännu. Endast din egen krypterade historik kan visas säkert.');return}const result=await loadOwnPlaceHistory();setHistory(Array.isArray(result.data)?result.data:[]);setHistoryError(result.error?.message||'')}catch(error){setHistory([]);setHistoryError(error?.message||'Historiken kunde inte hämtas.')}finally{setHistoryLoading(false)}}
 function toggleFollowLive(){setHistoryOpen(false);setCardNotice('');setLiveError('');setFollowLive((c)=>!c)}
 return <div className={`family-map-view${followLive?' is-following-live':''}`}>
 {entries.length>1?<div className="family-map-person-switcher" aria-label="Välj familjemedlem på kartan">{entries.map((entry)=><button key={entry.key} type="button" aria-pressed={entry.key===selectedEntry.key} onClick={()=>{setSelectedKey(entry.key);setHistoryOpen(false);setCardNotice('')}}>📍 {entry.label}</button>)}</div>:null}
 {followLive?<div className="family-map-live-bar"><strong>🟢 Följer live · {selectedEntry.label}</strong><span>Uppdaterar var 5:e sekund medan kartan är öppen</span></div>:null}
 <div className="family-map-frame"><iframe key={`${selectedEntry.key}:${selectedLocation.location_recorded_at||''}`} title={`Karta – ${selectedEntry.label}`} src={mapUrlForLocation(selectedLocation)} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div>{liveError?<p className="family-map-card-notice" role="alert">{liveError}</p>:null}
 <article className="family-map-person-card" aria-live="polite"><div className="family-map-person-card-heading"><strong>{selectedEntry.label}</strong><span className={isLive?'is-live':''}>{isLive?'🟢 LIVE':'Senaste position'}</span></div><p>📍 Delad position</p>{homeDistanceText?<p>🏠 {homeDistanceText}</p>:<small>Spara en trygg plats med namnet Hem för att visa avstånd hem.</small>}<small>Senast uppdaterad: {updatedLabel}</small>{selectedLocation.accuracy_meters!=null?<small>Noggrannhet ±{Math.round(selectedLocation.accuracy_meters)} m</small>:null}<div className="family-map-person-actions"><button type="button" aria-pressed={followLive} onClick={toggleFollowLive}>{followLive?'Sluta följa':'Följ live'}</button><button type="button" onClick={()=>setCardNotice('Prata kopplas in när röstfunktionen är klar.')}>Prata</button><button type="button" onClick={openHistory}>Historik</button></div><label className="family-map-frequency"><span>Positionsfrekvens</span><select value={positionFrequency} onChange={(e)=>setPositionFrequency(e.target.value)}>{positionFrequencyOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{cardNotice?<p className="family-map-card-notice" role="status">{cardNotice}</p>:null}</article>
 {historyOpen?<section className="family-map-history" aria-label={`Historik – ${selectedEntry.label}`}><div className="family-map-history-heading"><strong>Historik · {selectedEntry.label}</strong><button type="button" onClick={()=>setHistoryOpen(false)}>Stäng</button></div><div className="family-map-history-periods">{historyPeriods.map(([v,l])=><button key={v} type="button" aria-pressed={historyPeriod===v} onClick={()=>setHistoryPeriod(v)}>{l}</button>)}</div>{historyLoading?<p>Hämtar historik…</p>:null}{historyError?<p className="family-map-card-notice" role="status">{historyError}</p>:null}{!historyLoading&&!historyError&&visibleHistory.length===0?<p>Ingen sparad position under perioden.</p>:null}{visibleHistory.length?<div className="family-map-history-list">{visibleHistory.map((p)=><article key={p.id}><strong>{historyPointDate(p).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><span>📍 {Number(p.latitude).toFixed(5)}, {Number(p.longitude).toFixed(5)}</span>{p.accuracyMeters!=null?<small>±{Math.round(p.accuracyMeters)} m</small>:null}</article>)}</div>:null}</section>:null}
 <div className="family-map-selected"><strong>Position</strong><span>{Number(selectedLocation.latitude).toFixed(5)}, {Number(selectedLocation.longitude).toFixed(5)}</span></div><p className="family-map-provider-note"><small>Kartan visas av OpenStreetMap. Endast området runt den valda delade positionen begärs när kartan öppnas.</small></p></div>
}
export default FamilyMapView