import { useEffect, useState } from 'react'
import { displayNameForUser } from '../../features/place/placeFamilyMemberService.js'
import { analyzeOwnPlaceRoutine } from '../../features/place/placeRoutinePatternService.js'
import { formatRelativeLocationUpdate, getOwnLocationStatus } from '../../features/place/placeLocationStatus.js'
function mapEmbedUrl(latitude,longitude){const lat=Number(latitude),lon=Number(longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return'';const d=.006,b=[lon-d,lat-d,lon+d,lat+d].join(',');return `https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(b)}&layer=mapnik&marker=${encodeURIComponent(`${lat},${lon}`)}`}
function mapLinkUrl(latitude,longitude){const lat=Number(latitude),lon=Number(longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return'';return `https://www.openstreetmap.org/?mlat=${encodeURIComponent(lat)}&mlon=${encodeURIComponent(lon)}#map=16/${encodeURIComponent(lat)}/${encodeURIComponent(lon)}`}
function PlaceLocationStatusPanel({activeSharingStatus,familyLocations,familyLocationsLoaded,familyMembers,sharingEnabled}){
 const[routine,setRoutine]=useState(null)
 useEffect(()=>{let cancelled=false;if(!sharingEnabled){setRoutine(null);return()=>{cancelled=true}}analyzeOwnPlaceRoutine().then(({data})=>{if(!cancelled)setRoutine(data||null)}).catch(()=>{if(!cancelled)setRoutine(null)});return()=>{cancelled=true}},[sharingEnabled,activeSharingStatus?.lastUpdatedAt])
 return <section className="place-card place-location-status-panel" aria-labelledby="place-location-status-title">
  <h2 id="place-location-status-title">📡 Platsstatus</h2>
  <p><strong>Din plats:</strong>{' '}{getOwnLocationStatus({sharingEnabled,active:activeSharingStatus?.active,paused:activeSharingStatus?.paused,lastUpdatedAt:activeSharingStatus?.lastUpdatedAt})}</p>
  {activeSharingStatus?.accuracyMeters!=null?<p><small>Noggrannhet ±{Math.round(activeSharingStatus.accuracyMeters)} m</small></p>:null}
  {routine?.ready?<div className="place-location-routine"><p><strong>🧭 Smart rutinanalys</strong></p><p>{routine.message}</p><small>Analyseras bara från din egen krypterade platshistorik på den här enheten · {routine.days} dagar · {routine.points} positioner.</small></div>:routine?<div className="place-location-routine"><p><strong>🧭 Smart rutinanalys</strong></p><small>Samlar underlag. Minst 3 dagar och 12 sparade positioner behövs. Nu: {routine.days} dagar · {routine.points} positioner.</small></div>:null}
  {familyLocationsLoaded&&familyLocations.length>0?<div className="place-location-status-family"><p><strong>Familjens senaste delade plats</strong></p><ul>{familyLocations.map(location=>{const name=location.display_name||displayNameForUser(familyMembers,location.user_id),embedUrl=mapEmbedUrl(location.latitude,location.longitude),externalUrl=mapLinkUrl(location.latitude,location.longitude);return <li key={`${location.family_id}:${location.user_id}`} className="place-location-map-card"><div className="place-location-map-meta"><strong>{name}</strong>{' '}<span>{formatRelativeLocationUpdate(location.location_recorded_at)}</span>{location.accuracy_meters!=null?<small> · ±{Math.round(location.accuracy_meters)} m</small>:null}</div>{embedUrl?<div className="place-location-map-wrap"><iframe className="place-location-map" src={embedUrl} title={`Karta för ${name}`} loading="lazy" referrerPolicy="no-referrer"/><a className="place-location-map-link" href={externalUrl} target="_blank" rel="noreferrer">Öppna större karta</a></div>:null}</li>})}</ul></div>:familyLocationsLoaded?<p><small>Ingen familjemedlem delar en aktuell plats just nu.</small></p>:<p><small>Hämtar platsstatus…</small></p>}
 </section>
}
export default PlaceLocationStatusPanel
