import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const root = join(dirname(fileURLToPath(import.meta.url)), '../../..')
const sql = readFileSync(join(root, 'supabase/migrations/20260926134500_billing_disposable_test_subscription.sql'), 'utf8')
const priorGuard = readFileSync(join(root, 'supabase/migrations/20260924084000_billing_pending_plan_apply.sql'), 'utf8')
const body = sql.replace(/--[^\n]*/g, '')

function sliceBetween(source, start, end) {
  const from = source.indexOf(start)
  const to = source.indexOf(end, from + start.length)
  return source.slice(from, to)
}

describe('BILL-7U2B disposable test fixture', () => {
  it('keeps the marker table and fixture RPCs service_role only', () => {
    expect(sql).toMatch(/DO NOT apply to staging/)
    expect(sql).toMatch(/DO NOT apply to production/)
    expect(sql).toMatch(/create table if not exists billing\.disposable_test_subscriptions/)
    expect(sql).toMatch(/enable row level security/)
    expect(sql).toMatch(/force row level security/)
    expect(sql).toMatch(/using \(false\)/)
    expect(sql).toMatch(/with check \(false\)/)
    expect(sql).toMatch(/revoke all on table billing\.disposable_test_subscriptions from public, anon, authenticated, service_role/)
    expect(sql).not.toMatch(/grant .* on table billing\.disposable_test_subscriptions/i)
    expect(sql).toMatch(/revoke delete on table billing\.subscriptions from public, anon, authenticated, service_role/)
    expect(sql).toMatch(/security definer/)
    expect(sql).toMatch(/set search_path = pg_catalog, pg_temp/)
    expect(sql).toMatch(/auth\.role\(\) is distinct from 'service_role'/)
    expect(sql).toMatch(/revoke all on function billing\.create_disposable_test_subscription\(text, timestamptz, timestamptz\) from public, anon, authenticated, service_role/)
    expect(sql).toMatch(/revoke all on function billing\.cleanup_disposable_test_subscription\(text\) from public, anon, authenticated, service_role/)
    expect(sql).toMatch(/revoke all on function billing\.disposable_fixture_delete_allowed\(text\) from public, anon, authenticated, service_role/)
    expect(sql).toMatch(/grant execute on function billing\.create_disposable_test_subscription\(text, timestamptz, timestamptz\) to service_role/)
    expect(sql).toMatch(/grant execute on function billing\.cleanup_disposable_test_subscription\(text\) to service_role/)
    expect(sql).not.toMatch(/grant execute on function billing\.disposable_fixture_delete_allowed/i)
    expect(sql).not.toMatch(/grant execute.*to (public|anon|authenticated)/i)
    expect(body).not.toMatch(/\btruncate\b/i)
    expect(body).not.toMatch(/\bcascade\b/i)
    expect(body).not.toMatch(/session_replication_role/)
    expect(body).not.toMatch(/drop trigger/i)
    expect(body).not.toMatch(/delete from billing\.plans\b/)
    expect(body).not.toMatch(/delete from billing\.plan_entitlements\b/)
    expect(body).not.toMatch(/delete from billing\.quota_reservations\b/)
    expect(body).not.toMatch(/delete from billing\.usage_events\b/)
    expect(body).not.toMatch(/\bis_test\b/)
  })

  it('preserves ordinary delete rejection and scopes the bypass to one marked id', () => {
    const guard = sliceBetween(body, 'create or replace function billing.guard_subscription_row()', 'create or replace function billing.create_disposable_test_subscription')
    expect(guard).toMatch(/if tg_op = 'DELETE' then/)
    expect(guard).toMatch(/if not billing\.disposable_fixture_delete_allowed\(old\.subscription_id\) then/)
    expect(guard).toMatch(/raise exception 'subscriptions are not deletable'/)
    expect(guard).toMatch(/current_period_end cannot be shortened/)
    expect(guard).toMatch(/current_period_end cannot be extended/)
    expect(guard).toMatch(/subscription identity and plan snapshot are immutable/)
    expect(priorGuard).toMatch(/raise exception 'subscriptions are not deletable'/)
    const allowed = sliceBetween(body, 'create or replace function billing.disposable_fixture_delete_allowed', 'create or replace function billing.guard_subscription_row')
    expect(allowed).toMatch(/current_setting\('billing\.disposable_cleanup_subscription_id', true\)/)
    expect(allowed).toMatch(/is not distinct from p_subscription_id/)
    expect(allowed).toMatch(/from billing\.disposable_test_subscriptions d/)
    expect(allowed).toMatch(/where d\.subscription_id = p_subscription_id/)
  })

  it('creates only a new active fixture and refuses to adopt an existing subscription', () => {
    const create = sliceBetween(body, 'create or replace function billing.create_disposable_test_subscription', 'create or replace function billing.cleanup_disposable_test_subscription')
    expect(create).toMatch(/p_plan_id text/)
    expect(create).toMatch(/p_period_start timestamptz/)
    expect(create).toMatch(/p_period_end timestamptz/)
    expect(create.slice(0, create.indexOf('as $$'))).not.toMatch(/p_subscription_id|p_user_id|p_status/)
    expect(create).toMatch(/pg_catalog\.gen_random_uuid\(\)/)
    expect(create).toMatch(/p_status => 'ACTIVE'/)
    expect(create).toMatch(/p_cancel_at_period_end => false/)
    expect(create).toMatch(/p_external_event_id => null/)
    expect(create).toMatch(/billing\.create_subscription\(/)
    const createdAt = create.indexOf('billing.create_subscription(')
    const markerAt = create.indexOf('insert into billing.disposable_test_subscriptions')
    expect(createdAt).toBeGreaterThan(-1)
    expect(markerAt).toBeGreaterThan(createdAt)
    expect(create).toMatch(/values \(created\.subscription_id, created\.user_id\)/)
  })

  it('cleans only the proven fixture after lock, quota refusal, and a transaction-local token', () => {
    const cleanup = sliceBetween(body, 'create or replace function billing.cleanup_disposable_test_subscription', 'revoke all on function billing.disposable_fixture_delete_allowed')
    const markerLock = cleanup.indexOf('for update')
    const userLock = cleanup.indexOf('order by s.subscription_id')
    const recheck = cleanup.indexOf('disposable_fixture_not_found', userLock)
    const unmarked = cleanup.indexOf('disposable_fixture_unsafe')
    const quota = cleanup.indexOf('from billing.quota_reservations')
    const usage = cleanup.indexOf('from billing.usage_events')
    const assignmentEvents = cleanup.indexOf('delete from billing.user_plan_assignment_events')
    const subscriptionEvents = cleanup.indexOf('delete from billing.subscription_events')
    const assignment = cleanup.indexOf('delete from billing.user_plan_assignments')
    const token = cleanup.indexOf("set_config('billing.disposable_cleanup_subscription_id', target.subscription_id, true)")
    const subscription = cleanup.indexOf('delete from billing.subscriptions')
    const marker = cleanup.indexOf('delete from billing.disposable_test_subscriptions')
    expect(markerLock).toBeGreaterThan(-1)
    expect(userLock).toBeGreaterThan(markerLock)
    expect(recheck).toBeGreaterThan(userLock)
    expect(unmarked).toBeGreaterThan(recheck)
    expect(quota).toBeGreaterThan(unmarked)
    expect(usage).toBeGreaterThan(quota)
    expect(cleanup).toMatch(/from billing\.quota_period_locks/)
    expect(assignmentEvents).toBeGreaterThan(usage)
    expect(subscriptionEvents).toBeGreaterThan(assignmentEvents)
    expect(assignment).toBeGreaterThan(subscriptionEvents)
    expect(token).toBeGreaterThan(assignment)
    expect(subscription).toBeGreaterThan(token)
    expect(marker).toBeGreaterThan(subscription)
    expect(cleanup).toMatch(/where e\.subscription_id = target\.subscription_id/)
    expect(cleanup).toMatch(/where a\.user_id = target\.user_id/)
    expect(cleanup).toMatch(/s\.subscription_id is distinct from target\.subscription_id/)
    expect(cleanup).toMatch(/not exists \(/)
    expect(cleanup).toMatch(/set_config\('billing\.disposable_cleanup_subscription_id', '', true\)/)
    expect(cleanup).not.toMatch(/delete from billing\.subscriptions s\s+where s\.user_id/)
  })
})
