import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const root = join(dirname(fileURLToPath(import.meta.url)), '../../..')
const sql = readFileSync(join(root, 'supabase/migrations/20260926140000_billing_mark_renewal_failed.sql'), 'utf8')
const body = sql.replace(/--[^\n]*/g, '')

describe('BILL-7Q failed renewal RPC', () => {
  it('moves only ACTIVE to PAST_DUE after a post-lock event recheck', () => {
    expect(sql).toMatch(/DO NOT apply to staging/)
    expect(sql).toMatch(/DO NOT apply to production/)
    expect(sql).toMatch(/create or replace function billing\.mark_renewal_failed/)
    expect(sql).not.toMatch(/create or replace function billing\.transition_subscription/)
    expect(sql).toMatch(/security definer/)
    expect(sql).toMatch(/set search_path = pg_catalog, pg_temp/)
    expect(sql).toMatch(/revoke all on function billing\.mark_renewal_failed\(text, text, timestamptz, timestamptz\) from public, anon, authenticated, service_role/)
    expect(sql).toMatch(/grant execute on function billing\.mark_renewal_failed\(text, text, timestamptz, timestamptz\) to service_role/)
    expect(sql).not.toMatch(/grant execute.*to (public|anon|authenticated)/i)
    expect(body).toMatch(/operation = 'renewal\.failed'/)
    expect(body).toMatch(/from_status = 'ACTIVE'/)
    expect(body).toMatch(/to_status = 'PAST_DUE'/)
    expect(body).toMatch(/to_plan_id = from_plan_id/)
    expect(body).toMatch(/to_pending_plan_id is not distinct from previous_pending_plan_id/)
    expect(body).toMatch(/existing\.status not in \('ACTIVE', 'PAST_DUE'\)/)
    expect(body).toMatch(/raise exception 'illegal_subscription_transition'/)
    expect(body).toMatch(/p_period_end is distinct from existing\.current_period_end/)
    expect(body).toMatch(/set\s+status = 'PAST_DUE',\s+past_due_grace_until = p_past_due_grace_until/)
    expect(body).not.toMatch(/\bset\s+plan_id\b/)
    expect(body).not.toMatch(/\bset\s+pending_plan_id\b/)
    expect(body).not.toMatch(/\bset\s+cancel_at_period_end\b/)
    expect(body).toMatch(/prior_operation = 'renewal\.failed'/)
    expect(body).toMatch(/prior_period is not distinct from p_period_end/)
    expect(body).toMatch(/raise exception 'duplicate_external_event'/)
    expect(body).toMatch(/when unique_violation then/)
    const lockAt = body.indexOf('for update')
    const recheckAt = body.indexOf('from billing.subscription_events e', lockAt)
    const periodAt = body.indexOf('p_period_end is distinct from existing.current_period_end')
    const updateAt = body.indexOf('update billing.subscriptions')
    expect(lockAt).toBeGreaterThan(-1)
    expect(recheckAt).toBeGreaterThan(lockAt)
    expect(periodAt).toBeGreaterThan(recheckAt)
    expect(updateAt).toBeGreaterThan(periodAt)
    expect(body.indexOf("raise exception 'duplicate_external_event'", lockAt)).toBeLessThan(updateAt)
    expect(body.slice(lockAt, updateAt)).toMatch(/prior_operation = 'renewal\.failed'/)
    expect(body.slice(lockAt, updateAt)).toMatch(/return existing/)
    expect(body.slice(periodAt, updateAt)).toMatch(/existing\.status = 'PAST_DUE'/)
    const insertAt = body.indexOf('insert into billing.subscription_events')
    expect(insertAt).toBeGreaterThan(updateAt)
    expect(body).toMatch(/from_status = to_status/)
    expect(body).toMatch(/operation = 'plan\.schedule'/)
    expect(body).toMatch(/operation = 'period\.advance'/)
    expect(body).not.toMatch(/user_plan_assignments|quota_reservations|user_entitlements/i)
    expect(body).not.toMatch(/stripe|sumup|klarna|checkout|webhook/i)
  })
})
