export const nutritionFoods = [
  {
    id: 'kyckling',
    name: 'Kyckling',
    aliases: ['kyckling', 'kycklingfile', 'kycklingfilé'],
    protein: 31,
    carbs: 0,
    fat: 4,
    calories: 165,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'notkott',
    name: 'Nötkött',
    aliases: ['notkott', 'nötkött', 'biff', 'fars', 'köttfärs', 'kottfars'],
    protein: 26,
    carbs: 0,
    fat: 12,
    calories: 220,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'flask',
    name: 'Fläsk',
    aliases: ['flask', 'fläsk', 'flaskkott', 'fläskkött'],
    protein: 24,
    carbs: 0,
    fat: 14,
    calories: 230,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'lax',
    name: 'Lax',
    aliases: ['lax'],
    protein: 20,
    carbs: 0,
    fat: 13,
    calories: 210,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'torsk',
    name: 'Torsk',
    aliases: ['torsk'],
    protein: 18,
    carbs: 0,
    fat: 1,
    calories: 85,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'tonfisk',
    name: 'Tonfisk',
    aliases: ['tonfisk'],
    protein: 25,
    carbs: 0,
    fat: 1,
    calories: 120,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'agg',
    name: 'Ägg',
    aliases: ['agg', 'ägg', 'aggen', 'äggen'],
    protein: 6,
    carbs: 0,
    fat: 5,
    calories: 75,
    category: 'protein',
    defaultServing: '1 st',
  },
  {
    id: 'kvarg',
    name: 'Kvarg',
    aliases: ['kvarg'],
    protein: 12,
    carbs: 4,
    fat: 1,
    calories: 75,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'keso',
    name: 'Keso',
    aliases: ['keso', 'cottage cheese'],
    protein: 12,
    carbs: 3,
    fat: 4,
    calories: 100,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'grekisk-yoghurt',
    name: 'Grekisk yoghurt',
    aliases: ['grekisk yoghurt', 'yoghurt'],
    protein: 8,
    carbs: 4,
    fat: 5,
    calories: 95,
    category: 'protein',
    defaultServing: '100 g',
  },
  {
    id: 'mjolk',
    name: 'Mjölk',
    aliases: ['mjolk', 'mjölk'],
    protein: 7,
    carbs: 10,
    fat: 3,
    calories: 95,
    category: 'dairy',
    defaultServing: '2 dl',
  },
  {
    id: 'ost',
    name: 'Ost',
    aliases: ['ost'],
    protein: 8,
    carbs: 0,
    fat: 10,
    calories: 125,
    category: 'dairy',
    defaultServing: '30 g',
  },
  {
    id: 'havregryn',
    name: 'Havregryn',
    aliases: ['havregryn', 'gröt', 'grot'],
    protein: 7,
    carbs: 30,
    fat: 4,
    calories: 190,
    category: 'carb',
    defaultServing: '50 g',
  },
  {
    id: 'ris',
    name: 'Ris',
    aliases: ['ris'],
    protein: 4,
    carbs: 45,
    fat: 0,
    calories: 205,
    category: 'carb',
    defaultServing: '150 g kokt',
  },
  {
    id: 'potatis',
    name: 'Potatis',
    aliases: ['potatis', 'potatisar'],
    protein: 3,
    carbs: 30,
    fat: 0,
    calories: 135,
    category: 'carb',
    defaultServing: '200 g',
  },
  {
    id: 'pasta',
    name: 'Pasta',
    aliases: ['pasta'],
    protein: 7,
    carbs: 45,
    fat: 1,
    calories: 220,
    category: 'carb',
    defaultServing: '150 g kokt',
  },
  {
    id: 'brod',
    name: 'Bröd',
    aliases: ['brod', 'bröd', 'macka', 'smorgas', 'smörgås'],
    protein: 4,
    carbs: 22,
    fat: 2,
    calories: 120,
    category: 'carb',
    defaultServing: '1 skiva',
  },
  {
    id: 'banan',
    name: 'Banan',
    aliases: ['banan'],
    protein: 1,
    carbs: 23,
    fat: 0,
    calories: 105,
    category: 'fruit',
    defaultServing: '1 st',
  },
  {
    id: 'apple',
    name: 'Äpple',
    aliases: ['apple', 'äpple', 'applen', 'äpplen'],
    protein: 0,
    carbs: 20,
    fat: 0,
    calories: 80,
    category: 'fruit',
    defaultServing: '1 st',
  },
  {
    id: 'apelsin',
    name: 'Apelsin',
    aliases: ['apelsin'],
    protein: 1,
    carbs: 15,
    fat: 0,
    calories: 65,
    category: 'fruit',
    defaultServing: '1 st',
  },
  {
    id: 'avokado',
    name: 'Avokado',
    aliases: ['avokado', 'avocado'],
    protein: 2,
    carbs: 9,
    fat: 15,
    calories: 160,
    category: 'fat',
    defaultServing: '1/2 st',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    aliases: ['broccoli'],
    protein: 3,
    carbs: 7,
    fat: 0,
    calories: 45,
    category: 'vegetable',
    defaultServing: '100 g',
  },
  {
    id: 'morotter',
    name: 'Morötter',
    aliases: ['morotter', 'morötter', 'morot'],
    protein: 1,
    carbs: 10,
    fat: 0,
    calories: 45,
    category: 'vegetable',
    defaultServing: '100 g',
  },
  {
    id: 'tomat',
    name: 'Tomat',
    aliases: ['tomat', 'tomater'],
    protein: 1,
    carbs: 4,
    fat: 0,
    calories: 25,
    category: 'vegetable',
    defaultServing: '100 g',
  },
  {
    id: 'gurka',
    name: 'Gurka',
    aliases: ['gurka'],
    protein: 1,
    carbs: 3,
    fat: 0,
    calories: 15,
    category: 'vegetable',
    defaultServing: '100 g',
  },
  {
    id: 'pizza',
    name: 'Pizza',
    aliases: ['pizza', 'pizzan'],
    protein: 25,
    carbs: 90,
    fat: 30,
    calories: 750,
    category: 'fast_food',
    defaultServing: '1 pizza',
  },
  {
    id: 'hamburgare',
    name: 'Hamburgare',
    aliases: ['hamburgare', 'burgare', 'hamburgaren'],
    protein: 25,
    carbs: 35,
    fat: 25,
    calories: 480,
    category: 'fast_food',
    defaultServing: '1 st',
  },
  {
    id: 'pommes',
    name: 'Pommes',
    aliases: ['pommes', 'pommes frites'],
    protein: 4,
    carbs: 50,
    fat: 18,
    calories: 380,
    category: 'fast_food',
    defaultServing: '1 portion',
  },
  {
    id: 'godis',
    name: 'Godis',
    aliases: ['godis'],
    protein: 1,
    carbs: 75,
    fat: 2,
    calories: 330,
    category: 'sweets',
    defaultServing: '100 g',
  },
  {
    id: 'choklad',
    name: 'Choklad',
    aliases: ['choklad'],
    protein: 5,
    carbs: 55,
    fat: 30,
    calories: 550,
    category: 'sweets',
    defaultServing: '100 g',
  },
  {
    id: 'chips',
    name: 'Chips',
    aliases: ['chips'],
    protein: 6,
    carbs: 50,
    fat: 35,
    calories: 540,
    category: 'snack',
    defaultServing: '100 g',
  },
  {
    id: 'lask',
    name: 'Läsk',
    aliases: ['lask', 'läsk', 'cola'],
    protein: 0,
    carbs: 33,
    fat: 0,
    calories: 135,
    category: 'soda',
    defaultServing: '33 cl',
  },
  {
    id: 'glass',
    name: 'Glass',
    aliases: ['glass'],
    protein: 4,
    carbs: 30,
    fat: 12,
    calories: 250,
    category: 'sweets',
    defaultServing: '100 g',
  },
]

export function getNutritionFoodById(id) {
  return nutritionFoods.find((food) => food.id === id) || null
}
