function round(value) {
  return Math.round((value + Number.EPSILON) * 10) / 10
}

function withServingNutrition(food) {
  const factor = food.defaultPortionGrams / 100

  return {
    ...food,
    calories: round(food.caloriesPer100g * factor),
    carbs: round(food.carbsPer100g * factor),
    defaultServing: food.defaultServing,
    fat: round(food.fatPer100g * factor),
    protein: round(food.proteinPer100g * factor),
  }
}

const foods = [
  {
    id: 'kyckling',
    name: 'Kyckling',
    aliases: ['kyckling', 'kycklingbröst', 'kycklingbrost', 'kycklingfile', 'kycklingfilé'],
    category: 'protein',
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatPer100g: 4,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'notkott',
    name: 'Nötkött',
    aliases: ['nötkött', 'notkott', 'biff', 'köttfärs', 'kottfars'],
    category: 'protein',
    caloriesPer100g: 220,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 12,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'flask',
    name: 'Fläsk',
    aliases: ['fläsk', 'flask', 'fläskkött', 'flaskkott'],
    category: 'protein',
    caloriesPer100g: 230,
    proteinPer100g: 24,
    carbsPer100g: 0,
    fatPer100g: 14,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'lax',
    name: 'Lax',
    aliases: ['lax'],
    category: 'protein',
    caloriesPer100g: 210,
    proteinPer100g: 20,
    carbsPer100g: 0,
    fatPer100g: 13,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'torsk',
    name: 'Torsk',
    aliases: ['torsk'],
    category: 'protein',
    caloriesPer100g: 85,
    proteinPer100g: 18,
    carbsPer100g: 0,
    fatPer100g: 1,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'tonfisk',
    name: 'Tonfisk',
    aliases: ['tonfisk'],
    category: 'protein',
    caloriesPer100g: 120,
    proteinPer100g: 25,
    carbsPer100g: 0,
    fatPer100g: 1,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'agg',
    name: 'Ägg',
    aliases: ['ägg', 'agg', 'äggen', 'aggen'],
    category: 'protein',
    caloriesPer100g: 125,
    proteinPer100g: 10,
    carbsPer100g: 0,
    fatPer100g: 8.3,
    defaultPortionGrams: 60,
    defaultServing: '1 st',
  },
  {
    id: 'kvarg',
    name: 'Kvarg',
    aliases: ['kvarg'],
    category: 'protein',
    caloriesPer100g: 75,
    proteinPer100g: 12,
    carbsPer100g: 4,
    fatPer100g: 1,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'keso',
    name: 'Keso',
    aliases: ['keso', 'cottage cheese'],
    category: 'protein',
    caloriesPer100g: 100,
    proteinPer100g: 12,
    carbsPer100g: 3,
    fatPer100g: 4,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'grekisk-yoghurt',
    name: 'Grekisk yoghurt',
    aliases: ['grekisk yoghurt', 'yoghurt'],
    category: 'protein',
    caloriesPer100g: 95,
    proteinPer100g: 8,
    carbsPer100g: 4,
    fatPer100g: 5,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'mjolk',
    name: 'Mjölk',
    aliases: ['mjölk', 'mjolk'],
    category: 'dairy',
    caloriesPer100g: 48,
    proteinPer100g: 3.5,
    carbsPer100g: 5,
    fatPer100g: 1.5,
    defaultPortionGrams: 200,
    defaultServing: '2 dl',
  },
  {
    id: 'ost',
    name: 'Ost',
    aliases: ['ost'],
    category: 'dairy',
    caloriesPer100g: 417,
    proteinPer100g: 27,
    carbsPer100g: 1,
    fatPer100g: 34,
    defaultPortionGrams: 30,
    defaultServing: '30 g',
  },
  {
    id: 'havregryn',
    name: 'Havregryn',
    aliases: ['havregryn', 'gröt', 'grot'],
    category: 'carb',
    caloriesPer100g: 380,
    proteinPer100g: 14,
    carbsPer100g: 60,
    fatPer100g: 7,
    defaultPortionGrams: 50,
    defaultServing: '50 g',
  },
  {
    id: 'ris',
    name: 'Ris',
    aliases: ['ris'],
    category: 'carb',
    caloriesPer100g: 137,
    proteinPer100g: 2.7,
    carbsPer100g: 30,
    fatPer100g: 0.2,
    defaultPortionGrams: 150,
    defaultServing: '150 g kokt',
  },
  {
    id: 'potatis',
    name: 'Potatis',
    aliases: ['potatis', 'potatisar'],
    category: 'carb',
    caloriesPer100g: 77,
    proteinPer100g: 2,
    carbsPer100g: 17,
    fatPer100g: 0.1,
    defaultPortionGrams: 200,
    defaultServing: '200 g',
  },
  {
    id: 'pasta',
    name: 'Pasta',
    aliases: ['pasta'],
    category: 'carb',
    caloriesPer100g: 147,
    proteinPer100g: 5,
    carbsPer100g: 30,
    fatPer100g: 0.8,
    defaultPortionGrams: 150,
    defaultServing: '150 g kokt',
  },
  {
    id: 'brod',
    name: 'Bröd',
    aliases: ['proteinbröd', 'proteinbrod', 'bröd', 'brod', 'macka', 'smörgås', 'smorgas'],
    category: 'carb',
    caloriesPer100g: 300,
    proteinPer100g: 10,
    carbsPer100g: 55,
    fatPer100g: 5,
    defaultPortionGrams: 40,
    defaultServing: '1 skiva',
  },
  {
    id: 'banan',
    name: 'Banan',
    aliases: ['banan', 'bananer'],
    category: 'fruit',
    caloriesPer100g: 88,
    proteinPer100g: 1,
    carbsPer100g: 19,
    fatPer100g: 0.3,
    defaultPortionGrams: 120,
    defaultServing: '1 st',
  },
  {
    id: 'apple',
    name: 'Äpple',
    aliases: ['äpple', 'apple', 'äpplen', 'applen'],
    category: 'fruit',
    caloriesPer100g: 53,
    proteinPer100g: 0.3,
    carbsPer100g: 12,
    fatPer100g: 0.2,
    defaultPortionGrams: 150,
    defaultServing: '1 st',
  },
  {
    id: 'apelsin',
    name: 'Apelsin',
    aliases: ['apelsin', 'apelsiner'],
    category: 'fruit',
    caloriesPer100g: 45,
    proteinPer100g: 0.9,
    carbsPer100g: 10,
    fatPer100g: 0.1,
    defaultPortionGrams: 145,
    defaultServing: '1 st',
  },
  {
    id: 'avokado',
    name: 'Avokado',
    aliases: ['avokado', 'avocado'],
    category: 'fat',
    caloriesPer100g: 160,
    proteinPer100g: 2,
    carbsPer100g: 9,
    fatPer100g: 15,
    defaultPortionGrams: 75,
    defaultServing: '1/2 st',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    aliases: ['broccoli'],
    category: 'vegetable',
    caloriesPer100g: 45,
    proteinPer100g: 3,
    carbsPer100g: 7,
    fatPer100g: 0.4,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'morotter',
    name: 'Morötter',
    aliases: ['morötter', 'morotter', 'morot'],
    category: 'vegetable',
    caloriesPer100g: 45,
    proteinPer100g: 1,
    carbsPer100g: 10,
    fatPer100g: 0.2,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'tomat',
    name: 'Tomat',
    aliases: ['tomat', 'tomater'],
    category: 'vegetable',
    caloriesPer100g: 25,
    proteinPer100g: 1,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'gurka',
    name: 'Gurka',
    aliases: ['gurka'],
    category: 'vegetable',
    caloriesPer100g: 15,
    proteinPer100g: 1,
    carbsPer100g: 3,
    fatPer100g: 0.1,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'gronsaker',
    name: 'Grönsaker',
    aliases: ['grönsaker', 'gronsaker'],
    category: 'vegetable',
    caloriesPer100g: 35,
    proteinPer100g: 2,
    carbsPer100g: 6,
    fatPer100g: 0.3,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'pizza',
    name: 'Pizza',
    aliases: ['pizza', 'pizzan'],
    category: 'fast_food',
    caloriesPer100g: 214,
    proteinPer100g: 7.1,
    carbsPer100g: 25.7,
    fatPer100g: 8.6,
    defaultPortionGrams: 350,
    defaultServing: '1 pizza',
  },
  {
    id: 'hamburgare',
    name: 'Hamburgare',
    aliases: ['hamburgare', 'hamburgaren', 'burgare'],
    category: 'fast_food',
    caloriesPer100g: 267,
    proteinPer100g: 13.9,
    carbsPer100g: 19.4,
    fatPer100g: 13.9,
    defaultPortionGrams: 180,
    defaultServing: '1 st',
  },
  {
    id: 'pommes',
    name: 'Pommes',
    aliases: ['pommes frites', 'pommes'],
    category: 'fast_food',
    caloriesPer100g: 253,
    proteinPer100g: 2.7,
    carbsPer100g: 33.3,
    fatPer100g: 12,
    defaultPortionGrams: 150,
    defaultServing: '1 portion',
  },
  {
    id: 'godis',
    name: 'Godis',
    aliases: ['godis'],
    category: 'sweets',
    caloriesPer100g: 330,
    proteinPer100g: 1,
    carbsPer100g: 75,
    fatPer100g: 2,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'choklad',
    name: 'Choklad',
    aliases: ['choklad'],
    category: 'sweets',
    caloriesPer100g: 550,
    proteinPer100g: 5,
    carbsPer100g: 55,
    fatPer100g: 30,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'chips',
    name: 'Chips',
    aliases: ['chips'],
    category: 'snack',
    caloriesPer100g: 540,
    proteinPer100g: 6,
    carbsPer100g: 50,
    fatPer100g: 35,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'lask',
    name: 'Läsk',
    aliases: ['cola zero', 'läsk', 'lask', 'cola'],
    category: 'soda',
    caloriesPer100g: 41,
    proteinPer100g: 0,
    carbsPer100g: 10,
    fatPer100g: 0,
    defaultPortionGrams: 330,
    defaultServing: '33 cl',
  },
  {
    id: 'glass',
    name: 'Glass',
    aliases: ['glass'],
    category: 'sweets',
    caloriesPer100g: 250,
    proteinPer100g: 4,
    carbsPer100g: 30,
    fatPer100g: 12,
    defaultPortionGrams: 100,
    defaultServing: '100 g',
  },
  {
    id: 'majonnas',
    name: 'Majonnäs',
    aliases: ['majonnäs', 'majonnas'],
    category: 'fat',
    caloriesPer100g: 720,
    proteinPer100g: 1,
    carbsPer100g: 1,
    fatPer100g: 78,
    defaultPortionGrams: 15,
    defaultServing: '1 msk',
  },
  {
    id: 'olivolja',
    name: 'Olivolja',
    aliases: ['olivolja'],
    category: 'fat',
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    defaultPortionGrams: 14,
    defaultServing: '1 msk',
  },
  {
    id: 'smor',
    name: 'Smör',
    aliases: ['smör', 'smor'],
    category: 'fat',
    caloriesPer100g: 720,
    proteinPer100g: 1,
    carbsPer100g: 1,
    fatPer100g: 81,
    defaultPortionGrams: 5,
    defaultServing: '1 tsk',
  },
  {
    id: 'socker',
    name: 'Socker',
    aliases: ['socker'],
    category: 'sweets',
    caloriesPer100g: 400,
    proteinPer100g: 0,
    carbsPer100g: 100,
    fatPer100g: 0,
    defaultPortionGrams: 4,
    defaultServing: '1 tsk',
  },
].map(withServingNutrition)

export const nutritionFoods = foods

export function getNutritionFoodById(id) {
  return nutritionFoods.find((food) => food.id === id) || null
}

export function getNutritionAliases() {
  return nutritionFoods.flatMap((food) => food.aliases.map((alias) => ({
    alias,
    food,
  })))
}
