-- Viktkollen nutrition food bank foundation
-- Official Livsmedelsverket values must be stored unchanged and attributed by source/version.

create table if not exists public.nutrition_food_bank (
  id bigint generated by default as identity primary key,
  source text not null,
  source_food_id text not null,
  source_version text not null,
  name text not null,
  normalized_name text not null,
  category text,
  calories_per_100g numeric,
  protein_per_100g numeric,
  carbs_per_100g numeric,
  fat_per_100g numeric,
  fiber_per_100g numeric,
  salt_per_100g numeric,
  source_payload jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  unique (source, source_food_id, source_version)
);

create index if not exists nutrition_food_bank_normalized_name_idx
  on public.nutrition_food_bank (normalized_name);

create index if not exists nutrition_food_bank_source_idx
  on public.nutrition_food_bank (source, source_version);

alter table public.nutrition_food_bank enable row level security;

revoke all on table public.nutrition_food_bank from anon, authenticated;
grant select on table public.nutrition_food_bank to authenticated;

drop policy if exists "Authenticated users can read nutrition food bank"
  on public.nutrition_food_bank;

create policy "Authenticated users can read nutrition food bank"
  on public.nutrition_food_bank
  for select
  to authenticated
  using (true);

comment on table public.nutrition_food_bank is
  'Read-only nutrition reference bank. Official source values must be preserved unchanged.';
